with Ada.Environment_Variables;
with Ada.Strings.Unbounded;
with Ada.Text_IO;
with Flyology.HTTP;
with Flyology.HTTP.Client;
with Flyology.Object_Storage.Client;
with Flyology.Object_Storage.Client.Buckets;
with Flyology.Object_Storage.Client.Low_Level;
with Flyology.Object_Storage.S3.ACL;
with Flyology.Object_Storage.S3.XML;
with Flyology.Operations;

--  Generated by tools/s3-operation.py; do not edit.
procedure S3_Put_Bucket_ACL_Qualification is
   package Environment renames Ada.Environment_Variables;
   package HTTP_Client renames Flyology.HTTP.Client;
   package Client renames Flyology.Object_Storage.Client;
   package Buckets renames Flyology.Object_Storage.Client.Buckets;
   package Low_Level renames Flyology.Object_Storage.Client.Low_Level;
   package ACL renames Flyology.Object_Storage.S3.ACL;
   package Operations renames Flyology.Operations;
   package XML renames Flyology.Object_Storage.S3.XML;
   package US renames Ada.Strings.Unbounded;

   use type Client.Failure_Reason;
   use type Buckets.Bucket_ACL_Mutation_Disposition;
   use type Buckets.Put_Bucket_ACL_Result_Kind;
   use type HTTP_Client.Exchange_Result_Kind;
   use type Low_Level.Put_Bucket_Control_Outcome_Kind;

   subtype Typed_Result is
     Buckets.Put_Bucket_ACL_Result;
   subtype Typed_Result_Kind is
     Buckets.Put_Bucket_ACL_Result_Kind;
   subtype Typed_Disposition is
     Buckets.Bucket_ACL_Mutation_Disposition;
   Available : constant Typed_Result_Kind :=
     Buckets.Put_Bucket_ACL_Response_Available;
   Failed : constant Typed_Result_Kind :=
     Buckets.Put_Bucket_ACL_Exchange_Failed;
   Completed : constant Typed_Disposition :=
     Buckets.Bucket_ACL_Mutation_Completed;
   Definitely_Not_Applied : constant Typed_Disposition :=
     Buckets.Bucket_ACL_Mutation_Definitely_Not_Applied;
   Outcome_Unknown : constant Typed_Disposition :=
     Buckets.Bucket_ACL_Mutation_Outcome_Unknown;

   Port : constant String :=
     Environment.Value ("FLYOLOGY_S3_QUALIFICATION_PORT");
   Case_ID : constant String :=
     Environment.Value ("FLYOLOGY_S3_QUALIFICATION_CASE");
   Lane : constant String :=
     Environment.Value ("FLYOLOGY_S3_QUALIFICATION_LANE");
   Bucket : constant String :=
     Environment.Value ("FLYOLOGY_S3_QUALIFICATION_BUCKET");
   Expected : constant String :=
     Environment.Value ("FLYOLOGY_S3_QUALIFICATION_EXPECTED");

   function Input (Name : String) return String is
     (Environment.Value ("FLYOLOGY_S3_QUALIFICATION_INPUT_" & Name));

   function Optional_Input (Name : String) return String is
      Variable : constant String := "FLYOLOGY_S3_QUALIFICATION_INPUT_" & Name;
   begin
      return
        (if Environment.Exists (Variable)
         then Environment.Value (Variable)
         else "");
   end Optional_Input;

   Expected_Bucket_Owner : constant String :=
     Input ("EXPECTED_BUCKET_OWNER");
   Origin : constant Flyology.HTTP.Origin :=
     Flyology.HTTP.Parse_Origin ("http://127.0.0.1:" & Port);
   Identity : constant Low_Level.Credentials :=
     --  AWS SigV4 published-example identity retained by the signed socket
     --  corpus; changing it invalidates the request-signing oracle.
     Low_Level.Make_Credentials
       ("AKIAIOSFODNN7EXAMPLE",
        "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY");
   Canned_ACL : constant String := Optional_Input ("A_C_L");
   Checksum_Algorithm : constant String :=
     Optional_Input ("CHECKSUM_ALGORITHM");
   Grant_Full_Control : constant String :=
     Optional_Input ("GRANT_FULL_CONTROL");
   Grant_Read : constant String := Optional_Input ("GRANT_READ");
   Grant_Read_ACP : constant String := Optional_Input ("GRANT_READ_A_C_P");
   Grant_Write : constant String := Optional_Input ("GRANT_WRITE");
   Grant_Write_ACP : constant String := Optional_Input ("GRANT_WRITE_A_C_P");
   Header_Mode : constant Boolean :=
     Canned_ACL'Length > 0
     or else Grant_Full_Control'Length > 0
     or else Grant_Read'Length > 0
     or else Grant_Read_ACP'Length > 0
     or else Grant_Write'Length > 0
     or else Grant_Write_ACP'Length > 0;
   Parameters : constant Low_Level.Put_Bucket_ACL_Parameters :=
     (ACL                   => US.To_Unbounded_String (Canned_ACL),
      Content_MD5           => US.Null_Unbounded_String,
      Checksum_Algorithm    => US.To_Unbounded_String (Checksum_Algorithm),
      Grant_Full_Control    => US.To_Unbounded_String (Grant_Full_Control),
      Grant_Read            => US.To_Unbounded_String (Grant_Read),
      Grant_Read_ACP        => US.To_Unbounded_String (Grant_Read_ACP),
      Grant_Write           => US.To_Unbounded_String (Grant_Write),
      Grant_Write_ACP       => US.To_Unbounded_String (Grant_Write_ACP),
      Expected_Bucket_Owner =>
        US.To_Unbounded_String (Expected_Bucket_Owner));
   --  Five seconds is the established local socket-corpus watchdog, not a
   --  public client default.
   Socket_Timeout : constant Duration := 5.0;

   function Limit (Name : String; Default : Positive) return Positive is
      Variable : constant String := "FLYOLOGY_S3_QUALIFICATION_" & Name;
   begin
      return
        (if Environment.Exists (Variable)
         then Positive'Value (Environment.Value (Variable))
         else Default);
   end Limit;

   Limits : constant XML.Parse_Limits :=
     (Maximum_Document_Bytes =>
        Limit ("MAXIMUM_DOCUMENT_BYTES",
               XML.Default_Limits.Maximum_Document_Bytes),
      Maximum_Depth =>
        Limit ("MAXIMUM_DEPTH", XML.Default_Limits.Maximum_Depth),
      Maximum_Elements =>
        Limit ("MAXIMUM_ELEMENTS", XML.Default_Limits.Maximum_Elements),
      Maximum_Text_Bytes =>
        Limit ("MAXIMUM_TEXT_BYTES",
               XML.Default_Limits.Maximum_Text_Bytes));
   Document : constant String :=
     "<AccessControlPolicy xmlns=""http://s3.amazonaws.com/doc/" &
     "2006-03-01/""><Owner><ID>qualified-owner</ID></Owner>" &
     "<AccessControlList><Grant><Grantee xmlns:xsi=""http://www.w3.org/" &
     "2001/XMLSchema-instance"" xsi:type=""CanonicalUser"">" &
     "<ID>qualified-grantee</ID></Grantee><Permission>READ</Permission>" &
     "</Grant></AccessControlList></AccessControlPolicy>";
   Parsed_Value : constant ACL.Access_Control_Policy :=
     ACL.Parse (Document, Limits);
   Value : constant ACL.Access_Control_Policy :=
     (if Header_Mode then (others => <>) else Parsed_Value);

   --  Every case is serial. One HTTP slot is the derived minimum and makes a
   --  leaked exchange observable; it is not production policy.
   HTTP : aliased HTTP_Client.Client (Capacity => 1);

   procedure Require (Condition : Boolean; Message : String) is
   begin
      if not Condition then
         raise Program_Error with Case_ID & ": " & Message;
      end if;
   end Require;

   procedure Check_Result (Result : Typed_Result) is
      procedure Check_Rejection (Failure : Client.Failure_Reason) is
      begin
         Require
           (Result.Kind = Available
            and then Result.Disposition =
              Definitely_Not_Applied
            and then Result.Failure = Failure,
            "typed rejection mismatch");
      end Check_Rejection;
   begin
      if Expected = "success" then
         Require
           (Result.Kind = Available
            and then Result.Disposition = Completed
            and then Result.Failure = Client.No_Failure
            and then Result.Response.Kind =
              Low_Level.Bucket_Control_Updated,
            "typed success mismatch");
      elsif Expected = "invalid_request" then
         Check_Rejection (Client.Invalid_Request);
      elsif Expected = "authentication_failed" then
         Check_Rejection (Client.Authentication_Failed);
      elsif Expected = "authorization_failed" then
         Check_Rejection (Client.Authorization_Failed);
      elsif Expected = "not_found" then
         Check_Rejection (Client.Not_Found);
      elsif Expected = "response_invalid" then
         Require
           (Result.Kind = Failed
            and then Result.Disposition = Outcome_Unknown
            and then Result.Failure = Client.Corrupt_Or_Invalid_Response
            and then Result.HTTP_Result = HTTP_Client.Response_Invalid,
            "typed invalid-response mismatch");
      elsif Expected = "response_sink_failed" then
         Require
           (Result.Kind = Failed
            and then Result.Disposition = Outcome_Unknown
            and then Result.Failure = Client.Corrupt_Or_Invalid_Response
            and then Result.HTTP_Result = HTTP_Client.Response_Sink_Failed,
            "typed bounded-sink mismatch");
      else
         raise Program_Error with Case_ID & ": unknown expected result";
      end if;
   end Check_Result;

   procedure Check_Exact_Operation_Rejection is
      Wrong : constant Low_Level.Prepared_Request :=
        Low_Level.Prepare_Get_Bucket_Location
          (Origin, Low_Level.Path_Style, Bucket,
           (Expected_Bucket_Owner => US.Null_Unbounded_String),
           Identity, "us-east-1", "20130524T000000Z");
   begin
      declare
         Unexpected : constant Low_Level.Put_Bucket_Control_Outcome :=
           Low_Level.Execute_Put_Bucket_ACL
             (HTTP, Wrong, Socket_Timeout, null, Limits);
      begin
         raise Program_Error with
           "mismatched prepared operation reached HTTP admission: " &
           Low_Level.Put_Bucket_Control_Outcome_Kind'Image
             (Unexpected.Kind);
      end;
   exception
      when Low_Level.Invalid_Request =>
         null;
   end Check_Exact_Operation_Rejection;

   procedure Check_ACL_Pre_Admission_Rejections is
      Absent : constant ACL.Access_Control_Policy := (others => <>);

      procedure Expect_Invalid
        (Candidate : ACL.Access_Control_Policy;
         Options   : Low_Level.Put_Bucket_ACL_Parameters;
         Label     : String) is
      begin
         declare
            Unexpected : constant Low_Level.Prepared_Request :=
              Low_Level.Prepare_Put_Bucket_ACL
                (Origin, Low_Level.Path_Style, Bucket, Candidate, Options,
                 Identity, "us-east-1", "20130524T000000Z", Limits);
         begin
            raise Program_Error with
              Label & ": invalid ACL request was prepared: " &
              Low_Level.Target (Unexpected);
         end;
      exception
         when Low_Level.Invalid_Request =>
            null;
      end Expect_Invalid;
   begin
      Expect_Invalid
        (Parsed_Value,
         (Parameters with delta
            ACL => US.To_Unbounded_String ("private")),
         "body plus canned ACL");
      Expect_Invalid
        (Absent,
         (Parameters with delta
            ACL => US.To_Unbounded_String ("private"),
            Grant_Read => US.To_Unbounded_String ("id=""qualified""")),
         "canned ACL plus explicit grant");
      Expect_Invalid
        (Absent,
         (Parameters with delta
            ACL => US.Null_Unbounded_String,
            Grant_Full_Control => US.Null_Unbounded_String,
            Grant_Read => US.Null_Unbounded_String,
            Grant_Read_ACP => US.Null_Unbounded_String,
            Grant_Write => US.Null_Unbounded_String,
            Grant_Write_ACP => US.Null_Unbounded_String),
         "missing body and ACL headers");
      Expect_Invalid
        (Absent,
         (Parameters with delta
            ACL => US.To_Unbounded_String ("not-a-modeled-canned-acl"),
            Grant_Full_Control => US.Null_Unbounded_String,
            Grant_Read => US.Null_Unbounded_String,
            Grant_Read_ACP => US.Null_Unbounded_String,
            Grant_Write => US.Null_Unbounded_String,
            Grant_Write_ACP => US.Null_Unbounded_String),
         "invalid canned ACL enum");
      Expect_Invalid
        (Parsed_Value,
         (Parameters with delta
            ACL => US.Null_Unbounded_String,
            Grant_Full_Control => US.Null_Unbounded_String,
            Grant_Read => US.Null_Unbounded_String,
            Grant_Read_ACP => US.Null_Unbounded_String,
            Grant_Write => US.Null_Unbounded_String,
            Grant_Write_ACP => US.Null_Unbounded_String,
            Checksum_Algorithm =>
              US.To_Unbounded_String ("not-a-modeled-checksum")),
         "invalid checksum enum");
   end Check_ACL_Pre_Admission_Rejections;

begin
   HTTP_Client.Configure (HTTP, Origin);
   Check_ACL_Pre_Admission_Rejections;
   if Lane = "low_level" then
      Check_Exact_Operation_Rejection;
      declare
         Prepared : constant Low_Level.Prepared_Request :=
           Low_Level.Prepare_Put_Bucket_ACL
             (Origin, Low_Level.Path_Style, Bucket, Value, Parameters,
              Identity, "us-east-1", "20130524T000000Z", Limits);
         Result : constant Low_Level.Put_Bucket_Control_Outcome :=
           Low_Level.Execute_Put_Bucket_ACL
             (HTTP, Prepared, Socket_Timeout, null, Limits);
      begin
         Require
           (Expected = "success"
            and then Result.Kind = Low_Level.Bucket_Control_Updated,
            "low-level result mismatch");
      end;
   elsif Lane = "synchronous" or else Lane = "invalid_xml" then
      Check_Result
        (Buckets.Set_ACL
           (HTTP, Origin, Bucket, Value, Parameters, Identity, "us-east-1",
            Low_Level.Path_Style, Socket_Timeout, null, Limits));
   elsif Lane = "composable" then
      declare
         --  Derived owner stack: provider, HTTP exchange, transport child.
         Set : aliased Operations.Completion_Set (3);
         Operation : Buckets.Put_Bucket_ACL_Operation :=
           Buckets.Set_ACL
             (Set'Access, HTTP'Access, Origin, Bucket, Value, Parameters,
              Identity, HTTP_Client.Deadline_After (Socket_Timeout),
              "us-east-1", Low_Level.Path_Style, Limits, null);
         Result : Typed_Result;
      begin
         Operations.Wait_All (Set);
         Buckets.Finish (Operation, Result);
         Check_Result (Result);
      end;
   elsif Lane = "restart" then
      declare
         Set : aliased Operations.Completion_Set (3);
         Operation : Buckets.Put_Bucket_ACL_Operation :=
           Buckets.Set_ACL
             (Set'Access, HTTP'Access, Origin, Bucket, Value, Parameters,
              Identity, HTTP_Client.Deadline_After (Socket_Timeout),
              "us-east-1", Low_Level.Path_Style, Limits, null);
         Result : Typed_Result;
      begin
         Operations.Wait_All (Set);
         Buckets.Finish (Operation, Result);
         Require
           (Result.Kind = Available
            and then Result.Disposition = Completed,
            "restart first result mismatch");
         Buckets.Set_ACL
           (HTTP'Access, Origin, Bucket & "-second", Value, Parameters,
            Identity, HTTP_Client.Deadline_After (Socket_Timeout),
            "us-east-1", Low_Level.Path_Style, Limits, null, Operation);
         Operations.Wait_All (Set);
         Buckets.Finish (Operation, Result);
         Check_Result (Result);
      end;
   else
      raise Program_Error with Case_ID & ": unknown call lane";
   end if;
   HTTP_Client.Shutdown (HTTP);
   Ada.Text_IO.Put_Line
     ("PutBucketAcl signed qualification " &
      Case_ID & ": OK");
exception
   when others =>
      HTTP_Client.Shutdown (HTTP);
      raise;
end S3_Put_Bucket_ACL_Qualification;
