#!/usr/bin/env python3
"""Emit deterministic S3 checksum vectors from independent local oracles."""

import base64
import hashlib
import shutil
import subprocess
import sys
import zlib


LENGTHS = (
    0, 1, 2, 3, 7, 8, 9, 15, 16, 17, 31, 32, 33, 63, 64, 65,
    127, 128, 129, 239, 240, 241, 255, 256, 511, 512, 1023, 1024,
    1025, 4095, 4096, 65535,
)


def payload(length: int) -> bytes:
    return bytes((index * 131 + length * 17 + index // 7) % 256
                 for index in range(length))


def reflected_crc(data: bytes, polynomial: int, width: int) -> bytes:
    mask = (1 << width) - 1
    value = mask
    for byte in data:
        value ^= byte
        for _ in range(8):
            value = ((value >> 1) ^ polynomial
                     if value & 1 else value >> 1)
    return (value ^ mask).to_bytes(width // 8, "big")


def xxhash(data: bytes, mode: str) -> bytes:
    executable = shutil.which("xxhsum")
    if executable is None:
        raise SystemExit("xxhsum 0.8.3 or newer is required")
    output = subprocess.run(
        (executable, mode), input=data, stdout=subprocess.PIPE,
        check=True,
    ).stdout.split()[0].decode("ascii")
    if output.startswith("XXH3_"):
        output = output[5:]
    return bytes.fromhex(output)


def vectors(data: bytes):
    yield "CRC32", zlib.crc32(data).to_bytes(4, "big")
    yield "CRC32C", reflected_crc(data, 0x82F63B78, 32)
    yield "CRC64NVME", reflected_crc(data, 0x9A6C9329AC4BC9B5, 64)
    yield "SHA1", hashlib.sha1(data).digest()
    yield "SHA256", hashlib.sha256(data).digest()
    yield "SHA512", hashlib.sha512(data).digest()
    yield "MD5", hashlib.md5(data).digest()
    yield "XXHASH64", xxhash(data, "-H1")
    yield "XXHASH3", xxhash(data, "-H3")
    yield "XXHASH128", xxhash(data, "-H2")


def main() -> None:
    print("# Generated by tools/generate_s3_checksum_corpus.py")
    print("# payload[i] = (i * 131 + length * 17 + i // 7) mod 256")
    print("# length<TAB>algorithm<TAB>canonical padded Base64")
    for length in LENGTHS:
        for algorithm, digest in vectors(payload(length)):
            encoded = base64.b64encode(digest).decode("ascii")
            print(f"{length}\t{algorithm}\t{encoded}")


if __name__ == "__main__":
    try:
        main()
    except BrokenPipeError:
        sys.exit(0)
