#!/usr/bin/env python3
"""Deterministic Ada wire-codec generation from the pinned S3 model."""

from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import s3_operation


SUPPORTED_PATTERNS = {"arn:[^:]+:(s3|s3express):.*"}

GENERATED_REGION_PREFIX = "S3 OPERATION GENERATOR"


@dataclass(frozen=True)
class XML_Node:
    identifier: str
    name: str
    parent: str
    shape: str
    scalar: bool
    attribute: bool
    attribute_namespace: str
    repeated: bool
    required: bool
    boolean: bool
    integer: bool
    timestamp: bool
    minimum_length: int
    maximum_length: int | None
    pattern: str
    enumeration: tuple[str, ...]


def materialize_generated_region(
    source: str,
    region: str,
    content: str,
    insertion_anchor: str,
) -> str:
    """Replace or insert one generator-owned region without touching peers."""
    begin = f"--  BEGIN {GENERATED_REGION_PREFIX}: {region}"
    notice = "--  Generated by tools/s3-operation.py; do not edit this region."
    end = f"--  END {GENERATED_REGION_PREFIX}: {region}"
    if source.count(begin) != source.count(end):
        raise s3_operation.Audit_Error(
            f"unbalanced generated source region: {region}"
        )
    if source.count(begin) > 1:
        raise s3_operation.Audit_Error(
            f"duplicate generated source region: {region}"
        )
    rendered_body = content.rstrip()
    rendered = begin + "\n" + notice
    if rendered_body:
        #  Keep region ownership metadata out of leading GNATdoc prose for
        #  the first generated declaration.
        rendered += "\n\n" + rendered_body
    rendered += "\n" + end
    if begin in source:
        start = source.index(begin)
        finish = source.index(end, start) + len(end)
        return source[:start] + rendered + source[finish:]
    if source.count(insertion_anchor) != 1:
        raise s3_operation.Audit_Error(
            f"generated source anchor is not unique: {region}"
        )
    return source.replace(
        insertion_anchor,
        rendered + "\n\n" + insertion_anchor,
        1,
    )


def _list_directory_low_level_spec() -> str:
    return """   --  Complete model-derived ListDirectoryBuckets inputs. Presence
   --  remains independent from an empty cursor or numeric zero. The caller
   --  selects the page size; this record supplies no default.
   type List_Directory_Buckets_Parameters is record
      Continuation_Token        : Ada.Strings.Unbounded.Unbounded_String;
      Has_Continuation_Token    : Boolean;
      Max_Directory_Buckets     : Natural;
      Has_Max_Directory_Buckets : Boolean;
   end record;

   --  Build and sign one exact ListDirectoryBuckets request. Origin must be
   --  the caller-selected S3 Express control endpoint.
   function Prepare_List_Directory_Buckets
     (Origin     : Flyology.HTTP.Origin;
      Parameters : List_Directory_Buckets_Parameters;
      Identity   : Credentials;
      Region     : String;
      Timestamp  : String) return Prepared_Request;

   type List_Directory_Buckets_Outcome_Kind is
     (Directory_Buckets_Listed, List_Directory_Buckets_Rejected);

   --  Kind selects the meaningful payload. All fields remain explicit so the
   --  low-level result is definite without inventing a status or discriminant
   --  default for an exchange that has not occurred.
   type List_Directory_Buckets_Outcome is record
      Kind   : List_Directory_Buckets_Outcome_Kind;
      Status : Flyology.HTTP.Status_Code;
      Result : S3.Buckets.List_Buckets_Result;
      Error  : S3.Errors.Error_Response;
   end record;

   function Decode_List_Directory_Buckets_Complete_Response
     (Response         : Flyology.HTTP.Client.Response;
      Payload          : String;
      Limits           : S3.XML.Parse_Limits;
      Collection_Limit : Positive)
      return List_Directory_Buckets_Outcome;

   function Execute_List_Directory_Buckets
     (Client           : aliased in out Flyology.HTTP.Client.Client;
      Prepared         : Prepared_Request;
      Timeout          : Duration;
      Token            : access Flyology.Cancellation.Token;
      Limits           : S3.XML.Parse_Limits;
      Collection_Limit : Positive)
      return List_Directory_Buckets_Outcome;

   procedure List_Directory_Buckets
     (Client    : not null access Flyology.HTTP.Client.Client;
      Prepared  : not null access constant Prepared_Request;
      Sink      : not null access
        Flyology.HTTP.Client.Response_Body_Sink'Class;
      Deadline  : Flyology.HTTP.Client.Monotonic_Deadline;
      Token     : access Flyology.Cancellation.Token;
      Operation : in out Flyology.HTTP.Client.Exchange_Operation);"""


def _list_directory_low_level_body() -> str:
    return """   function Prepare_List_Directory_Buckets
     (Origin     : Flyology.HTTP.Origin;
      Parameters : List_Directory_Buckets_Parameters;
      Identity   : Credentials;
      Region     : String;
      Timestamp  : String) return Prepared_Request
   is
      Optional_Count : constant Natural :=
        Boolean'Pos (Parameters.Has_Continuation_Token) +
        Boolean'Pos (Parameters.Has_Max_Directory_Buckets);
      Values : Model_Value_Array (1 .. Optional_Count);
      Last   : Natural := 0;

      procedure Add (Name, Value : String) is
      begin
         Last := Last + 1;
         Values (Last) :=
           (Member_Name => US.To_Unbounded_String (Name),
            Map_Key     => US.Null_Unbounded_String,
            Value       => US.To_Unbounded_String (Value));
      end Add;
   begin
      if Parameters.Has_Continuation_Token then
         Add
           ("ContinuationToken",
            US.To_String (Parameters.Continuation_Token));
      end if;
      if Parameters.Has_Max_Directory_Buckets then
         Add
           ("MaxDirectoryBuckets",
            Ada.Strings.Fixed.Trim
              (Natural'Image (Parameters.Max_Directory_Buckets),
               Ada.Strings.Both));
      end if;
      return Prepare_Model_Request
        (Model.List_Directory_Buckets_Operation, Origin, Path_Style, Values,
         "", False, SigV4.Empty_Payload_Hash, Identity, Region, Timestamp);
   end Prepare_List_Directory_Buckets;

   function Decode_List_Directory_Buckets_Complete_Response
     (Response         : Flyology.HTTP.Client.Response;
      Payload          : String;
      Limits           : S3.XML.Parse_Limits;
      Collection_Limit : Positive)
      return List_Directory_Buckets_Outcome
   is
      function Singleton_Header (Name : String) return String is
         Count : constant Natural :=
           Flyology.HTTP.Client.Header_Count (Response, Name);
      begin
         if Count > 1 then
            raise Invalid_Response with
              "invalid ListDirectoryBuckets response header multiplicity";
         elsif Count = 0 then
            return "";
         end if;
         declare
            Value : constant String :=
              Flyology.HTTP.Client.Header (Response, Name);
         begin
            if Value'Length = 0
              or else not Valid_List_Response_Header_Text (Value)
            then
               raise Invalid_Response with
                 "invalid ListDirectoryBuckets response header";
            end if;
            return Value;
         end;
      end Singleton_Header;

      Status     : constant Flyology.HTTP.Status_Code :=
        Flyology.HTTP.Client.Status (Response);
      Request_ID : constant String := Singleton_Header ("x-amz-request-id");
      Host_ID    : constant String := Singleton_Header ("x-amz-id-2");
   begin
      if Status = 200 then
         return
           (Kind   => Directory_Buckets_Listed,
            Status => Status,
            Result =>
              S3.Generated_List_Directory_Buckets_XML.Parse
                (Payload, Limits, Collection_Limit),
            Error  => (others => <>));
      end if;
      return
        (Kind   => List_Directory_Buckets_Rejected,
         Status => Status,
         Result => (others => <>),
         Error  => Error_Response (Payload, Request_ID, Host_ID, Limits));
   exception
      when S3.Generated_List_Directory_Buckets_XML.Malformed_Document |
           S3.Errors.Malformed_Error | Constraint_Error =>
         raise Invalid_Response with
           "malformed ListDirectoryBuckets response";
   end Decode_List_Directory_Buckets_Complete_Response;

   function Execute_List_Directory_Buckets
     (Client           : aliased in out Flyology.HTTP.Client.Client;
      Prepared         : Prepared_Request;
      Timeout          : Duration;
      Token            : access Flyology.Cancellation.Token;
      Limits           : S3.XML.Parse_Limits;
      Collection_Limit : Positive)
      return List_Directory_Buckets_Outcome is
   begin
      if Prepared.Operation /= Model_Driven_Operation
        or else Prepared.Modeled_Operation /=
          Model.List_Directory_Buckets_Operation
      then
         raise Invalid_Request with "prepared request operation mismatch";
      end if;
      declare
         Response : Flyology.HTTP.Client.Response :=
           Flyology.HTTP.Client.Execute
             (Client, Prepared.Message, Timeout, Token);
         Payload : constant Flyology.Bytes.Unbounded_Bytes :=
           Flyology.HTTP.Client.Read_All
             (Response, Limits.Maximum_Document_Bytes, Token);
      begin
         return Decode_List_Directory_Buckets_Complete_Response
           (Response, Flyology.Bytes.To_Byte_String (Payload), Limits,
            Collection_Limit);
      end;
   exception
      when Flyology.HTTP.Client.Response_Too_Large =>
         raise Invalid_Response with
           "ListDirectoryBuckets response exceeds configured limit";
   end Execute_List_Directory_Buckets;

   procedure List_Directory_Buckets
     (Client    : not null access Flyology.HTTP.Client.Client;
      Prepared  : not null access constant Prepared_Request;
      Sink      : not null access
        Flyology.HTTP.Client.Response_Body_Sink'Class;
      Deadline  : Flyology.HTTP.Client.Monotonic_Deadline;
      Token     : access Flyology.Cancellation.Token;
      Operation : in out Flyology.HTTP.Client.Exchange_Operation) is
   begin
      Start_Model_Sink
        (S3.Model.List_Directory_Buckets_Operation, Client, Prepared, Sink,
         Deadline, Token, Operation);
   end List_Directory_Buckets;"""


def _list_directory_provider_spec() -> str:
    return """   --  Shape of a terminal ListDirectoryBuckets read.
   --  @enum List_Directory_Buckets_Response_Available Modeled page exists
   --  @enum List_Directory_Buckets_Exchange_Failed No complete response exists
   type List_Directory_Buckets_Result_Kind is
     (List_Directory_Buckets_Response_Available,
      List_Directory_Buckets_Exchange_Failed);

   --  Typed bounded directory-bucket page or composable HTTP failure.
   --  This is a read-only operation; it has no mutation disposition or retry
   --  authority. The caller supplies the S3 Express control endpoint and all
   --  resource limits.
   --  @field Kind Result shape
   --  @field Failure Bounded expected failure reason
   --  @field Admission HTTP admission certainty at terminal completion
   --  @field Response Complete modeled S3 response
   --  @field HTTP_Result Typed HTTP terminal outcome
   --  @field HTTP_Phase Causal HTTP phase
   --  @field Detail Bounded sanitized HTTP diagnostic
   type List_Directory_Buckets_Result
     (Kind : List_Directory_Buckets_Result_Kind :=
       List_Directory_Buckets_Exchange_Failed)
   is record
      --  Public initialization contract: an unassigned result denotes no
      --  admitted exchange and no valid response. These defaults are scratch
      --  state only; they do not classify an observed S3 response.
      Failure   : Failure_Reason := Corrupt_Or_Invalid_Response;
      Admission : Flyology.HTTP.Client.Admission_Certainty :=
        Flyology.HTTP.Client.Not_Admitted;
      case Kind is
         when List_Directory_Buckets_Response_Available =>
            Response : Low_Level.List_Directory_Buckets_Outcome;
         when List_Directory_Buckets_Exchange_Failed =>
            HTTP_Result : Flyology.HTTP.Client.Exchange_Result_Kind :=
              Flyology.HTTP.Client.Response_Invalid;
            HTTP_Phase : Flyology.HTTP.Client.Exchange_Phase :=
              Flyology.HTTP.Client.Not_Started;
            Detail : Ada.Strings.Unbounded.Unbounded_String;
      end case;
   end record;

   --  One bounded ListDirectoryBuckets parent with one hidden HTTP child.
   --  The operation owns its prepared request and bounded response bytes
   --  through typed Finish and retains only its selected client and optional
   --  cancellation token through terminal drain.
   type List_Directory_Buckets_Operation
     (Set          : not null access Flyology.Operations.Completion_Set'Class;
      HTTP         : not null access Flyology.HTTP.Client.Client;
      Cancellation : access Flyology.Cancellation.Token) is
     new Flyology.Operations.Operation
     and Flyology.HTTP.Client.Response_Body_Sink with private;

   --  Start or restart one directory-bucket page read.
   --  @param Client Configured control-endpoint client retained through drain
   --  @param Origin Caller-selected S3 Express control endpoint
   --  @param Parameters Complete modeled cursor and page-size presence
   --  @param Identity Credentials borrowed only during signing
   --  @param Deadline Absolute whole-exchange deadline
   --  @param Region SigV4 region
   --  @param Limits Caller-selected response and error XML limits
   --  @param Collection_Limit Caller-selected maximum decoded bucket count
   --  @param Token Caller-selected cancellation source or null
   --  @param Operation Fresh or consumed established directory listing
   procedure List_Directory_Buckets
     (Client           : not null access Flyology.HTTP.Client.Client;
      Origin           : Flyology.HTTP.Origin;
      Parameters       : Low_Level.List_Directory_Buckets_Parameters;
      Identity         : Low_Level.Credentials;
      Deadline         : Flyology.HTTP.Client.Monotonic_Deadline;
      Region           : String;
      Limits           : Flyology.Object_Storage.S3.XML.Parse_Limits;
      Collection_Limit : Positive;
      Token            : access Flyology.Cancellation.Token;
      Operation        : in out List_Directory_Buckets_Operation)
   with
     Pre =>
       not Flyology.Operations.Is_Active (Operation)
       and then not Flyology.Operations.Is_Terminal (Operation);

   --  Construct one owner-driven directory-bucket page read.
   --  @param Set Caller-owned completion set
   --  @param Client Configured control-endpoint client retained through drain
   --  @param Origin Caller-selected S3 Express control endpoint
   --  @param Parameters Complete modeled cursor and page-size presence
   --  @param Identity Credentials borrowed only during signing
   --  @param Deadline Absolute whole-exchange deadline
   --  @param Region SigV4 region
   --  @param Limits Caller-selected response and error XML limits
   --  @param Collection_Limit Caller-selected maximum decoded bucket count
   --  @param Token Caller-selected cancellation source or null
   --  @return Started owner-driven directory-bucket listing
   function List_Directory_Buckets
     (Set              : not null access
        Flyology.Operations.Completion_Set'Class;
      Client           : not null access Flyology.HTTP.Client.Client;
      Origin           : Flyology.HTTP.Origin;
      Parameters       : Low_Level.List_Directory_Buckets_Parameters;
      Identity         : Low_Level.Credentials;
      Deadline         : Flyology.HTTP.Client.Monotonic_Deadline;
      Region           : String;
      Limits           : Flyology.Object_Storage.S3.XML.Parse_Limits;
      Collection_Limit : Positive;
      Token            : access Flyology.Cancellation.Token)
      return List_Directory_Buckets_Operation;

   --  Consume one terminal ListDirectoryBuckets operation.
   --  @param Operation Terminal directory-bucket listing
   --  @param Result Typed modeled page or bounded exchange failure
   procedure Finish
     (Operation : in out List_Directory_Buckets_Operation;
      Result    : out List_Directory_Buckets_Result)
   with Pre => Flyology.Operations.Is_Terminal (Operation);

   --  Read one directory-bucket page by waiting on the same owner-driven
   --  state machine used by composable callers. The wrapper does not start a
   --  hidden continuation request.
   function List_Directory_Buckets
     (Client           : aliased in out Flyology.HTTP.Client.Client;
      Origin           : Flyology.HTTP.Origin;
      Parameters       : Low_Level.List_Directory_Buckets_Parameters;
      Identity         : Low_Level.Credentials;
      Region           : String;
      Timeout          : Duration;
      Token            : access Flyology.Cancellation.Token;
      Limits           : Flyology.Object_Storage.S3.XML.Parse_Limits;
      Collection_Limit : Positive)
      return List_Directory_Buckets_Result;"""


def _list_directory_provider_private_spec() -> str:
    return """   --  @exclude
   function Decode_List_Directory_Buckets_Response
     (Status           : Flyology.HTTP.Status_Code;
      Response         : Flyology.HTTP.Client.Response;
      Payload          : String;
      Request_ID       : String;
      Host_ID          : String;
      Limits           : Flyology.Object_Storage.S3.XML.Parse_Limits;
      Collection_Limit : Positive;
      Admission        : Flyology.HTTP.Client.Admission_Certainty;
      Phase            : Flyology.HTTP.Client.Exchange_Phase)
      return List_Directory_Buckets_Result;

   --  @exclude
   function Normalize_List_Directory_Buckets_Failure
     (Kind      : Flyology.HTTP.Client.Exchange_Result_Kind;
      Admission : Flyology.HTTP.Client.Admission_Certainty;
      Phase     : Flyology.HTTP.Client.Exchange_Phase;
      Detail    : String) return List_Directory_Buckets_Result;

   --  @exclude
   package List_Directory_Buckets_Reads is new
     Flyology.Object_Storage.Client.Paginated_REST_XML_Reads
       (Result_Type       => List_Directory_Buckets_Result,
        Operation_Name    => "ListDirectoryBuckets",
        Start_Exchange    => Low_Level.List_Directory_Buckets,
        Decode_Response   => Decode_List_Directory_Buckets_Response,
        Normalize_Failure => Normalize_List_Directory_Buckets_Failure);

   --  @exclude
   --  Legal private completion of the visible limited operation type above.
   type List_Directory_Buckets_Operation
     (Set          : not null access Flyology.Operations.Completion_Set'Class;
      HTTP         : not null access Flyology.HTTP.Client.Client;
      Cancellation : access Flyology.Cancellation.Token) is
     new Flyology.Operations.Operation (Set)
     and Flyology.HTTP.Client.Response_Body_Sink
   with record
      State : List_Directory_Buckets_Reads.State (Set);
   end record;

   --  @exclude
   overriding procedure Write
     (Item : in out List_Directory_Buckets_Operation;
      Data : Ada.Streams.Stream_Element_Array);
   --  @exclude
   overriding procedure Drive
     (Item  : in out List_Directory_Buckets_Operation;
      Event : Flyology.Operations.Driver_Event);
   --  @exclude
   overriding procedure Request_Cancellation
     (Item : in out List_Directory_Buckets_Operation);
   --  @exclude
   overriding procedure Finalize
     (Item : in out List_Directory_Buckets_Operation);"""


def _list_directory_provider_body() -> str:
    return """   function Normalize_List_Directory_Buckets_Response
     (Value     : Low_Level.List_Directory_Buckets_Outcome;
      Admission : HTTP_Client.Admission_Certainty;
      Phase     : HTTP_Client.Exchange_Phase)
      return List_Directory_Buckets_Result
   is
      use type Low_Level.List_Directory_Buckets_Outcome_Kind;

      Code : constant String :=
        (if Value.Kind = Low_Level.List_Directory_Buckets_Rejected
         then US.To_String (Value.Error.Code)
         else "");
      Failure : constant Failure_Reason :=
        (if Admission /= HTTP_Client.Response_Observed
         then Corrupt_Or_Invalid_Response
         elsif Value.Kind = Low_Level.Directory_Buckets_Listed
         then No_Failure
         elsif Value.Status = 401 and then Code = "InvalidAccessKeyId"
         then Authentication_Failed
         elsif Value.Status = 403 and then Code = "AccessDenied"
         then Authorization_Failed
         elsif Value.Status = 400
           and then Code in "InvalidArgument" | "InvalidRequest"
         then Invalid_Request
         elsif (Value.Status = 409 and then Code = "OperationAborted")
           or else (Value.Status = 429 and then Code = "SlowDown")
           or else (Value.Status = 500 and then Code = "InternalError")
           or else (Value.Status = 502 and then Code = "BadGateway")
           or else (Value.Status = 503 and then Code = "SlowDown")
           or else (Value.Status = 504 and then Code = "RequestTimeout")
         then Unavailable_Or_Retryable
         else Corrupt_Or_Invalid_Response);
      pragma Unreferenced (Phase);
   begin
      return
        (Kind      => List_Directory_Buckets_Response_Available,
         Failure   => Failure,
         Admission => Admission,
         Response  => Value);
   end Normalize_List_Directory_Buckets_Response;

   function Decode_List_Directory_Buckets_Response
     (Status           : Flyology.HTTP.Status_Code;
      Response         : HTTP_Client.Response;
      Payload          : String;
      Request_ID       : String;
      Host_ID          : String;
      Limits           : Flyology.Object_Storage.S3.XML.Parse_Limits;
      Collection_Limit : Positive;
      Admission        : HTTP_Client.Admission_Certainty;
      Phase            : HTTP_Client.Exchange_Phase)
      return List_Directory_Buckets_Result is
      pragma Unreferenced (Status, Request_ID, Host_ID);
   begin
      return Normalize_List_Directory_Buckets_Response
        (Low.Decode_List_Directory_Buckets_Complete_Response
           (Response, Payload, Limits, Collection_Limit),
         Admission, Phase);
   exception
      when Error : Low.Invalid_Response =>
         return Normalize_List_Directory_Buckets_Failure
           (HTTP_Client.Response_Invalid, Admission, Phase,
            Ada.Exceptions.Exception_Message (Error));
   end Decode_List_Directory_Buckets_Response;

   function Normalize_List_Directory_Buckets_Failure
     (Kind      : HTTP_Client.Exchange_Result_Kind;
      Admission : HTTP_Client.Admission_Certainty;
      Phase     : HTTP_Client.Exchange_Phase;
      Detail    : String) return List_Directory_Buckets_Result is
   begin
      return
        (Kind        => List_Directory_Buckets_Exchange_Failed,
         Failure     =>
           (if Kind
               in HTTP_Client.Response_Invalid
                | HTTP_Client.Response_Body_Too_Large
                | HTTP_Client.Response_Sink_Failed
            then Corrupt_Or_Invalid_Response
            else Failed_Reason (Kind)),
         Admission   => Admission,
         HTTP_Result => Kind,
         HTTP_Phase  => Phase,
         Detail      => US.To_Unbounded_String (Detail));
   end Normalize_List_Directory_Buckets_Failure;

   overriding procedure Write
     (Item : in out List_Directory_Buckets_Operation;
      Data : Ada.Streams.Stream_Element_Array) is
   begin
      List_Directory_Buckets_Reads.Write (Item.State, Data);
   end Write;

   overriding procedure Drive
     (Item  : in out List_Directory_Buckets_Operation;
      Event : Operations.Driver_Event) is
   begin
      List_Directory_Buckets_Reads.Drive
        (Item.State, Item'Access, Item'Access, Item.HTTP,
         Item.Cancellation, Event);
   end Drive;

   overriding procedure Request_Cancellation
     (Item : in out List_Directory_Buckets_Operation) is
   begin
      List_Directory_Buckets_Reads.Request_Cancellation (Item.State);
   end Request_Cancellation;

   overriding procedure Finalize
     (Item : in out List_Directory_Buckets_Operation) is
   begin
      begin
         Operations.Finalize (Operations.Operation (Item));
      exception
         when others => null;
      end;
      List_Directory_Buckets_Reads.Finalize (Item.State);
   end Finalize;

   procedure List_Directory_Buckets
     (Client           : not null access HTTP_Client.Client;
      Origin           : Flyology.HTTP.Origin;
      Parameters       : Low_Level.List_Directory_Buckets_Parameters;
      Identity         : Low_Level.Credentials;
      Deadline         : HTTP_Client.Monotonic_Deadline;
      Region           : String;
      Limits           : Flyology.Object_Storage.S3.XML.Parse_Limits;
      Collection_Limit : Positive;
      Token            : access Flyology.Cancellation.Token;
      Operation        : in out List_Directory_Buckets_Operation) is
   begin
      if Operation.HTTP /= Client or else Operation.Cancellation /= Token then
         raise Program_Error with
           "ListDirectoryBuckets restart changed owner";
      end if;
      List_Directory_Buckets_Reads.Start
        (Operation.State, Operation'Access,
         Low.Prepare_List_Directory_Buckets
           (Origin, Parameters, Identity, Region, Timestamp),
         Deadline, Limits, Collection_Limit);
   end List_Directory_Buckets;

   function List_Directory_Buckets
     (Set              : not null access Operations.Completion_Set'Class;
      Client           : not null access HTTP_Client.Client;
      Origin           : Flyology.HTTP.Origin;
      Parameters       : Low_Level.List_Directory_Buckets_Parameters;
      Identity         : Low_Level.Credentials;
      Deadline         : HTTP_Client.Monotonic_Deadline;
      Region           : String;
      Limits           : Flyology.Object_Storage.S3.XML.Parse_Limits;
      Collection_Limit : Positive;
      Token            : access Flyology.Cancellation.Token)
      return List_Directory_Buckets_Operation is
   begin
      return Result : List_Directory_Buckets_Operation (Set, Client, Token) do
         List_Directory_Buckets
           (Client, Origin, Parameters, Identity, Deadline, Region, Limits,
            Collection_Limit, Token, Result);
      end return;
   end List_Directory_Buckets;

   procedure Finish
     (Operation : in out List_Directory_Buckets_Operation;
      Result    : out List_Directory_Buckets_Result) is
   begin
      List_Directory_Buckets_Reads.Finish
        (Operation.State, Operation'Access, Result);
   end Finish;

   function List_Directory_Buckets
     (Client           : aliased in out HTTP_Client.Client;
      Origin           : Flyology.HTTP.Origin;
      Parameters       : Low_Level.List_Directory_Buckets_Parameters;
      Identity         : Low_Level.Credentials;
      Region           : String;
      Timeout          : Duration;
      Token            : access Flyology.Cancellation.Token;
      Limits           : Flyology.Object_Storage.S3.XML.Parse_Limits;
      Collection_Limit : Positive)
      return List_Directory_Buckets_Result
   is
      --  Derived owner stack: provider parent, HTTP exchange, and HTTP's one
      --  active transport child. This is not a caller resource default.
      Set : aliased Operations.Completion_Set (3);
   begin
      declare
         Operation : List_Directory_Buckets_Operation :=
           List_Directory_Buckets
             (Set'Access, Client'Access, Origin, Parameters, Identity,
              HTTP_Client.Deadline_After (Timeout), Region, Limits,
              Collection_Limit, Token);
         Result : List_Directory_Buckets_Result;
      begin
         Operations.Wait_All (Set);
         Finish (Operation, Result);
         return Result;
      end;
   end List_Directory_Buckets;"""


def ada_identifier(value: str) -> str:
    value = s3_operation.camel_to_ada(value)
    words = re.findall(r"[A-Za-z]+|[0-9]+", value)
    result = "_".join(word.capitalize() for word in words)
    if not result or result[0].isdigit():
        result = "Node_" + result
    return result


def ada_string(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def payload_shape(
    model: dict[str, Any], operation: str, entry: dict[str, Any]
) -> str:
    modeled = s3_operation.output_payload_shape(model, operation)
    return entry.get("negative_xml", {}).get("payload_shape", modeled)


def xml_nodes(
    model: dict[str, Any], operation: str, entry: dict[str, Any]
) -> list[XML_Node]:
    """Expand the response payload into occurrence-specific XML nodes."""
    shapes = model["shapes"]
    root_shape = payload_shape(model, operation, entry)
    root_name = shapes[root_shape].get("locationName", root_shape)
    nodes: list[XML_Node] = []
    identifiers: set[str] = set()

    def identifier(path: tuple[str, ...]) -> str:
        base = ada_identifier("_".join(path))
        candidate = base
        suffix = 2
        while candidate in identifiers:
            candidate = f"{base}_{suffix}"
            suffix += 1
        identifiers.add(candidate)
        return candidate

    def add_node(
        *,
        path: tuple[str, ...],
        name: str,
        parent: str,
        shape_name: str,
        attribute: bool = False,
        attribute_namespace: str = "",
        repeated: bool = False,
        required: bool = False,
    ) -> str:
        shape = shapes[shape_name]
        kind = shape["type"]
        if kind in {"blob", "map"}:
            raise s3_operation.Audit_Error(
                f"strict XML generator does not support {kind}: "
                f"{operation}/{shape_name}"
            )
        node_id = identifier(path)
        nodes.append(
            XML_Node(
                identifier=node_id,
                name=name,
                parent=parent,
                shape=shape_name,
                scalar=kind not in {"structure", "list"},
                attribute=attribute,
                attribute_namespace=attribute_namespace,
                repeated=repeated,
                required=required,
                boolean=kind == "boolean",
                integer=kind in {"integer", "long"},
                timestamp=kind == "timestamp",
                minimum_length=(
                    int(shape.get("min", 0)) if kind == "string" else 0
                ),
                maximum_length=(
                    int(shape["max"])
                    if kind == "string" and "max" in shape
                    else None
                ),
                pattern=str(shape.get("pattern", "")),
                enumeration=tuple(shape.get("enum", [])),
            )
        )
        if kind == "structure":
            add_structure(shape_name, node_id, path)
        elif kind == "list":
            add_list(shape_name, node_id, path, required=False)
        return node_id

    active: list[str] = []

    def add_structure(
        shape_name: str, parent: str, path: tuple[str, ...]
    ) -> None:
        if shape_name in active:
            raise s3_operation.Audit_Error(
                f"recursive XML shape requires human design: "
                f"{operation}/{shape_name}"
            )
        active.append(shape_name)
        shape = shapes[shape_name]
        required_members = set(shape.get("required", []))
        for member_name, member in shape.get("members", {}).items():
            location = member.get("location", "body")
            attribute = bool(member.get("xmlAttribute", False))
            if location != "body" and not attribute:
                continue
            target_name = member["shape"]
            target = shapes[target_name]
            tag = member.get(
                "locationName", member.get("xmlName", member_name)
            )
            member_path = (*path, member_name)
            if attribute:
                namespace = member.get("xmlNamespace", {}).get("uri", "")
                raw_tag = tag
                if ":" in raw_tag:
                    prefix, raw_tag = raw_tag.split(":", 1)
                    shape_namespace = shape.get("xmlNamespace", {})
                    if shape_namespace.get("prefix") == prefix:
                        namespace = shape_namespace.get("uri", namespace)
                add_node(
                    path=member_path,
                    name=raw_tag,
                    parent=parent,
                    shape_name=target_name,
                    attribute=True,
                    attribute_namespace=namespace,
                    required=member_name in required_members,
                )
            elif target["type"] == "list":
                flattened = bool(
                    member.get("flattened", False)
                    or target.get("flattened", False)
                )
                if flattened:
                    add_list(
                        target_name,
                        parent,
                        member_path,
                        required=member_name in required_members,
                        flattened_tag=tag,
                    )
                else:
                    container = add_node(
                        path=member_path,
                        name=tag,
                        parent=parent,
                        shape_name=target_name,
                        required=member_name in required_members,
                    )
                    # add_node expands list members itself.
                    assert container
            else:
                add_node(
                    path=member_path,
                    name=tag,
                    parent=parent,
                    shape_name=target_name,
                    required=member_name in required_members,
                )
        active.pop()

    def add_list(
        shape_name: str,
        parent: str,
        path: tuple[str, ...],
        *,
        required: bool,
        flattened_tag: str | None = None,
    ) -> None:
        shape = shapes[shape_name]
        member = shape["member"]
        item_shape = member["shape"]
        item = shapes[item_shape]
        item_name = flattened_tag or member.get(
            "locationName", item.get("locationName", item_shape)
        )
        add_node(
            path=(*path, "Item"),
            name=item_name,
            parent=parent,
            shape_name=item_shape,
            repeated=True,
            required=required or int(shape.get("min", 0)) > 0,
        )

    root_id = add_node(
        path=("Root",),
        name=root_name,
        parent="No_Element",
        shape_name=root_shape,
    )
    if root_id != "Root":
        raise AssertionError("root identifier generation changed")
    return nodes


def codec_plan(
    model: dict[str, Any], operation: str, entry: dict[str, Any]
) -> dict[str, Any]:
    nodes = xml_nodes(model, operation, entry)
    return {
        "operation": operation,
        "package": (
            "Flyology.Object_Storage.S3.Generated_"
            + ada_identifier(operation)
            + "_XML"
        ),
        "payload_shape": payload_shape(model, operation, entry),
        "node_count": len(nodes),
        "nodes": [node.__dict__ for node in nodes],
        "strict_contract": {
            "duplicate_singletons": "reject",
            "unknown_members": "reject",
            "required_members": "reject_when_absent",
            "enumerations": "exact_model_domain",
            "namespaces": "unqualified_or_exact_s3_consistently",
            "attributes": "exact_model_domain",
            "patterns": "exact_supported_model_domain",
            "xml_limits": "caller_supplied",
            "collection_limit": "caller_supplied_without_default",
        },
        "unsupported_generator_traits": [
            {
                "element": node.identifier,
                "trait": "pattern",
                "value": node.pattern,
            }
            for node in nodes
            if node.pattern and node.pattern not in SUPPORTED_PATTERNS
        ],
    }


def _true_cases(nodes: list[XML_Node], field: str) -> list[str]:
    return [node.identifier for node in nodes if getattr(node, field)]


def _boolean_function(name: str, nodes: list[XML_Node], field: str) -> str:
    cases = _true_cases(nodes, field)
    expression = (
        "Element in " + " | ".join(cases) if cases else "False"
    )
    return (
        f"   function {name} (Element : Element_Id) return Boolean is\n"
        f"     ({expression});\n"
    )


def codec_descriptor_text(
    model: dict[str, Any], operation: str, entry: dict[str, Any]
) -> tuple[str, str, str]:
    """Return filename, generated descriptor spec, and descriptor body."""
    nodes = xml_nodes(model, operation, entry)
    patterns = [
        node
        for node in nodes
        if node.pattern and node.pattern not in SUPPORTED_PATTERNS
    ]
    if patterns:
        raise s3_operation.Audit_Error(
            "strict XML scaffold lacks modeled pattern support: "
            + ", ".join(
                f"{node.identifier}={node.pattern}" for node in patterns
            )
        )
    package = (
        "Flyology.Object_Storage.S3.Generated_"
        + ada_identifier(operation)
        + "_XML"
    )
    typed_bucket_list = entry.get("generation", {}).get(
        "response_representation"
    ) == "Flyology.Object_Storage.S3.Buckets.List_Buckets_Result"
    unit = package.lower().replace(".", "-")
    identifiers = ["No_Element", *(node.identifier for node in nodes)]
    spec_withs = ["with Flyology.Object_Storage.S3.XML;"]
    if typed_bucket_list:
        spec_withs.append("with Flyology.Object_Storage.S3.Buckets;")
    typed_spec = []
    if typed_bucket_list:
        typed_spec = [
            "",
            "   Malformed_Document : exception;",
            "",
            "   function Parse",
            "     (Document         : String;",
            "      Limits           : XML.Parse_Limits;",
            "      Collection_Limit : Positive)",
            "      return Flyology.Object_Storage.S3.Buckets.List_Buckets_Result;",
        ]
    spec = "\n".join(
        [
            *spec_withs,
            "",
            "--  Generated by tools/s3-operation.py; do not edit.",
            f"--  Operation: {operation}",
            f"--  Botocore revision: {s3_operation.EXPECTED_MODEL_REVISION}",
            "--  Model SHA-256:",
            f"--    {s3_operation.EXPECTED_MODEL_SHA256}",
            "pragma Style_Checks (Off);",
            f"package {package} is",
            "",
            "   type Element_Id is",
            "     (" + ",\n      ".join(identifiers) + ");",
            "",
            "   Root_Element : constant Element_Id := Root;",
            "",
            "   function Element_Name (Element : Element_Id) return String;",
            "   function Parent (Element : Element_Id) return Element_Id;",
            "   function Is_Scalar (Element : Element_Id) return Boolean;",
            "   function Is_Attribute (Element : Element_Id) return Boolean;",
            "   function Attribute_Namespace",
            "     (Element : Element_Id) return String;",
            "   function Is_Repeated (Element : Element_Id) return Boolean;",
            "   function Is_Required (Element : Element_Id) return Boolean;",
            "   function Is_Boolean (Element : Element_Id) return Boolean;",
            "   function Is_Integer (Element : Element_Id) return Boolean;",
            "   function Is_Timestamp (Element : Element_Id) return Boolean;",
            "   function Minimum_Length (Element : Element_Id) return Natural;",
            "   function Has_Maximum_Length",
            "     (Element : Element_Id) return Boolean;",
            "   function Maximum_Length (Element : Element_Id) return Natural;",
            "   function Enumeration_Count (Element : Element_Id) return Natural;",
            "   function Enumeration_Value",
            "     (Element : Element_Id; Index : Positive) return String;",
            "   function Matches_Pattern",
            "     (Element : Element_Id; Value : String) return Boolean;",
            "",
            "   generic",
            "      type Result_Type is limited private;",
            "      with procedure Start_Node",
            "        (Result : in out Result_Type; Element : Element_Id);",
            "      with procedure Set_Scalar",
            "        (Result : in out Result_Type; Element : Element_Id;",
            "         Value : String);",
            "      with procedure End_Node",
            "        (Result : in out Result_Type; Element : Element_Id);",
            "   package Decoder is",
            "      Malformed_Document : exception;",
            "      procedure Parse",
            "        (Document         : String;",
            "         Limits           : XML.Parse_Limits;",
            "         Collection_Limit : Positive;",
            "         Result           : aliased in out Result_Type);",
            "   end Decoder;",
            *typed_spec,
            "",
            f"end {package};",
            "",
        ]
    )

    def case_function(name: str, values: dict[str, str], default: str) -> str:
        lines = [f"   function {name} (Element : Element_Id) return String is",
                 "   begin", "      case Element is"]
        for node_id, value in values.items():
            lines.extend(
                (f"         when {node_id} =>",
                 f"            return {ada_string(value)};")
            )
        lines.extend(("         when others =>", f"            return {ada_string(default)};",
                      "      end case;", f"   end {name};", ""))
        return "\n".join(lines)

    body_withs = "with Flyology.Object_Storage.S3.Strict_XML_Codecs;\n"
    if typed_bucket_list:
        body_withs += "with Ada.Strings.Unbounded;\n"
    body_parts = [
        body_withs + "\n"
        "--  Generated by tools/s3-operation.py; do not edit.\n"
        f"--  Operation: {operation}\n"
        "pragma Style_Checks (Off);\n"
        f"package body {package} is\n",
        case_function(
            "Element_Name",
            {node.identifier: node.name for node in nodes},
            "",
        ),
    ]
    parent_values = {node.identifier: node.parent for node in nodes}
    lines = ["   function Parent (Element : Element_Id) return Element_Id is",
             "   begin", "      case Element is"]
    for node_id, parent in parent_values.items():
        lines.extend((f"         when {node_id} =>", f"            return {parent};"))
    lines.extend(("         when No_Element =>", "            return No_Element;",
                  "      end case;", "   end Parent;", ""))
    body_parts.append("\n".join(lines))
    for function_name, field in (
        ("Is_Scalar", "scalar"),
        ("Is_Attribute", "attribute"),
        ("Is_Repeated", "repeated"),
        ("Is_Required", "required"),
        ("Is_Boolean", "boolean"),
        ("Is_Integer", "integer"),
        ("Is_Timestamp", "timestamp"),
        ("Has_Maximum_Length", "maximum_length"),
    ):
        body_parts.append(_boolean_function(function_name, nodes, field))
    body_parts.append(
        case_function(
            "Attribute_Namespace",
            {
                node.identifier: node.attribute_namespace
                for node in nodes
                if node.attribute
            },
            "",
        )
    )
    for function_name, field in (
        ("Minimum_Length", "minimum_length"),
        ("Maximum_Length", "maximum_length"),
    ):
        value_lines = [
            f"   function {function_name}",
            "     (Element : Element_Id) return Natural is",
            "   begin",
            "      case Element is",
        ]
        for node in nodes:
            value = getattr(node, field)
            if value not in (None, 0):
                value_lines.extend(
                    (f"         when {node.identifier} =>",
                     f"            return {value};")
                )
        value_lines.extend(
            ("         when others =>", "            return 0;",
             "      end case;", f"   end {function_name};", "")
        )
        body_parts.append("\n".join(value_lines))
    count_lines = [
        "   function Enumeration_Count",
        "     (Element : Element_Id) return Natural is",
        "   begin",
        "      case Element is",
    ]
    for node in nodes:
        if node.enumeration:
            count_lines.extend(
                (f"         when {node.identifier} =>",
                 f"            return {len(node.enumeration)};")
            )
    count_lines.extend(("         when others =>", "            return 0;",
                        "      end case;", "   end Enumeration_Count;", ""))
    body_parts.append("\n".join(count_lines))
    enum_nodes = [node for node in nodes if node.enumeration]
    enum_lines = [
        "   function Enumeration_Value",
        "     (Element : Element_Id; Index : Positive) return String is",
    ]
    if not enum_nodes:
        enum_lines.extend(
            ("      pragma Unreferenced (Element, Index);",
             "   begin",
             "      return (raise Constraint_Error);",
             "   end Enumeration_Value;",
             "")
        )
    else:
        enum_lines.extend(("   begin", "      case Element is"))
        for node in enum_nodes:
            enum_lines.append(f"         when {node.identifier} =>")
            enum_lines.append("            case Index is")
            for index, value in enumerate(node.enumeration, 1):
                enum_lines.extend(
                    (f"               when {index} =>",
                     f"                  return {ada_string(value)};")
                )
            enum_lines.extend(
                ("               when others =>",
                 "                  raise Constraint_Error;",
                 "            end case;")
            )
        enum_lines.extend(
            ("         when others =>", "            raise Constraint_Error;",
             "      end case;", "   end Enumeration_Value;", "")
        )
    body_parts.append("\n".join(enum_lines))
    if any(node.pattern for node in nodes):
        body_parts.append(
            "\n".join(
                (
                    "   function Matches_S3_Bucket_ARN",
                    "     (Value : String) return Boolean is",
                    "      Service_Start : Integer;",
                    "      Separator     : Integer;",
                    "   begin",
                    "      if Value'Length < 8",
                    "        or else Value (Value'First .. Value'First + 3) /= \"arn:\"",
                    "      then",
                    "         return False;",
                    "      end if;",
                    "      Service_Start := Value'First + 4;",
                    "      Separator := Service_Start;",
                    "      while Separator <= Value'Last",
                    "        and then Value (Separator) /= ':'",
                    "      loop",
                    "         Separator := Separator + 1;",
                    "      end loop;",
                    "      if Separator = Service_Start or else Separator > Value'Last then",
                    "         return False;",
                    "      end if;",
                    "      Service_Start := Separator + 1;",
                    "      return",
                    "        (Service_Start + 2 <= Value'Last",
                    "         and then Value (Service_Start .. Service_Start + 2) = \"s3:\")",
                    "        or else",
                    "        (Service_Start + 9 <= Value'Last",
                    "         and then Value (Service_Start .. Service_Start + 9) =",
                    "           \"s3express:\");",
                    "   end Matches_S3_Bucket_ARN;",
                    "",
                )
            )
        )
    pattern_lines = [
        "   function Matches_Pattern",
        "     (Element : Element_Id; Value : String) return Boolean is",
        "   begin",
        "      case Element is",
    ]
    for node in nodes:
        if node.pattern == "arn:[^:]+:(s3|s3express):.*":
            pattern_lines.extend(
                (
                    f"         when {node.identifier} =>",
                    "            return Matches_S3_Bucket_ARN (Value);",
                )
            )
    pattern_lines.extend(
        (
            "         when others =>",
            "            return True;",
            "      end case;",
            "   end Matches_Pattern;",
            "",
        )
    )
    body_parts.append("\n".join(pattern_lines))
    body_parts.append(
        "\n".join(
            (
                "   package body Decoder is",
                "      package Runtime is new",
                "        Flyology.Object_Storage.S3.Strict_XML_Codecs",
                "        (Element_Id          => Element_Id,",
                "         No_Element         => No_Element,",
                "         Root_Element       => Root_Element,",
                "         Element_Name       => Element_Name,",
                "         Parent             => Parent,",
                "         Is_Scalar          => Is_Scalar,",
                "         Is_Attribute       => Is_Attribute,",
                "         Attribute_Namespace => Attribute_Namespace,",
                "         Is_Repeated        => Is_Repeated,",
                "         Is_Required        => Is_Required,",
                "         Is_Boolean         => Is_Boolean,",
                "         Is_Integer         => Is_Integer,",
                "         Is_Timestamp       => Is_Timestamp,",
                "         Minimum_Length     => Minimum_Length,",
                "         Has_Maximum_Length => Has_Maximum_Length,",
                "         Maximum_Length     => Maximum_Length,",
                "         Enumeration_Count  => Enumeration_Count,",
                "         Enumeration_Value  => Enumeration_Value,",
                "         Matches_Pattern    => Matches_Pattern,",
                "         Result_Type        => Result_Type,",
                "         Start_Node         => Start_Node,",
                "         Set_Scalar         => Set_Scalar,",
                "         End_Node           => End_Node);",
                "",
                "      procedure Parse",
                "        (Document         : String;",
                "         Limits           : XML.Parse_Limits;",
                "         Collection_Limit : Positive;",
                "         Result           : aliased in out Result_Type) is",
                "      begin",
                "         Runtime.Parse",
                "           (Document, Limits, Collection_Limit, Result);",
                "      exception",
                "         when Runtime.Malformed_Document =>",
                "            raise Malformed_Document;",
                "      end Parse;",
                "   end Decoder;",
                "",
            )
        )
    )
    if typed_bucket_list:
        body_parts.append(
            """   package US renames Ada.Strings.Unbounded;

   type Parse_State is record
      Value   : Flyology.Object_Storage.S3.Buckets.List_Buckets_Result;
      Current : Flyology.Object_Storage.S3.Buckets.Bucket_Entry;
   end record;

   procedure Start_Node
     (Result : in out Parse_State; Element : Element_Id) is
   begin
      if Element = Root_Buckets_Item then
         Result.Current := (others => <>);
      end if;
   end Start_Node;

   procedure Set_Scalar
     (Result  : in out Parse_State;
      Element : Element_Id;
      Value   : String) is
   begin
      case Element is
         when Root_Buckets_Item_Name =>
            Result.Current.Name := US.To_Unbounded_String (Value);
         when Root_Buckets_Item_Creation_Date =>
            Result.Current.Creation_Date := US.To_Unbounded_String (Value);
         when Root_Buckets_Item_Bucket_Region =>
            Result.Current.Bucket_Region := US.To_Unbounded_String (Value);
         when Root_Buckets_Item_Bucket_Arn =>
            Result.Current.Bucket_ARN := US.To_Unbounded_String (Value);
         when Root_Continuation_Token =>
            Result.Value.Continuation_Token := US.To_Unbounded_String (Value);
            Result.Value.Has_Continuation_Token := True;
         when others =>
            null;
      end case;
   end Set_Scalar;

   procedure End_Node
     (Result : in out Parse_State; Element : Element_Id) is
   begin
      if Element = Root_Buckets_Item then
         Result.Value.Buckets.Append (Result.Current);
      end if;
   end End_Node;

   package Typed_Decoder is new Decoder
     (Result_Type => Parse_State,
      Start_Node  => Start_Node,
      Set_Scalar  => Set_Scalar,
      End_Node    => End_Node);

   function Parse
     (Document         : String;
      Limits           : XML.Parse_Limits;
      Collection_Limit : Positive)
      return Flyology.Object_Storage.S3.Buckets.List_Buckets_Result
   is
      State : aliased Parse_State;
   begin
      Typed_Decoder.Parse (Document, Limits, Collection_Limit, State);
      return State.Value;
   exception
      when Typed_Decoder.Malformed_Document =>
         raise Malformed_Document;
   end Parse;
"""
        )
    body_parts.append(f"end {package};\n")
    return unit, spec, "\n".join(body_parts)


@dataclass(frozen=True)
class Mutation_Serializer:
    payload_shape: str
    value_unit: str
    value_type: str
    closure_sha256: str
    body: str


MUTATION_SERIALIZERS = {
    "PutBucketInventoryConfiguration": Mutation_Serializer(
        payload_shape="InventoryConfiguration",
        value_unit="Inventory",
        value_type="Inventory_Configuration",
        closure_sha256=(
            "daf86b2bb14d64c87ee951bed9157fea6eafd9304487f43b6f4ee857059ed9b8"
        ),
        body="""   function Inventory_Format_Image
     (Value : Inventory.Inventory_Format) return String is
     (case Value is
         when Inventory.CSV     => "CSV",
         when Inventory.ORC     => "ORC",
         when Inventory.Parquet => "Parquet");

   function Frequency_Image
     (Value : Inventory.Inventory_Frequency) return String is
     (case Value is
         when Inventory.Daily  => "Daily",
         when Inventory.Weekly => "Weekly");

   function Versions_Image
     (Value : Inventory.Included_Object_Versions) return String is
     (case Value is
         when Inventory.All_Versions     => "All",
         when Inventory.Current_Versions => "Current");

   function Optional_Field_Image
     (Value : Inventory.Optional_Field_Kind) return String is
     (case Value is
         when Inventory.Size => "Size",
         when Inventory.Last_Modified_Date => "LastModifiedDate",
         when Inventory.Storage_Class => "StorageClass",
         when Inventory.ETag => "ETag",
         when Inventory.Is_Multipart_Uploaded => "IsMultipartUploaded",
         when Inventory.Replication_Status => "ReplicationStatus",
         when Inventory.Encryption_Status => "EncryptionStatus",
         when Inventory.Object_Lock_Retain_Until_Date =>
           "ObjectLockRetainUntilDate",
         when Inventory.Object_Lock_Mode => "ObjectLockMode",
         when Inventory.Object_Lock_Legal_Hold_Status =>
           "ObjectLockLegalHoldStatus",
         when Inventory.Intelligent_Tiering_Access_Tier =>
           "IntelligentTieringAccessTier",
         when Inventory.Bucket_Key_Status => "BucketKeyStatus",
         when Inventory.Checksum_Algorithm => "ChecksumAlgorithm",
         when Inventory.Object_Access_Control_List =>
           "ObjectAccessControlList",
         when Inventory.Object_Owner => "ObjectOwner",
         when Inventory.Lifecycle_Expiration_Date =>
           "LifecycleExpirationDate");

   function Serialize
     (Value  : Inventory.Inventory_Configuration;
      Limits : XML.Parse_Limits) return String
   is
      Item : XML_Writers.Writer;
      S3_Destination : Inventory.S3_Bucket_Destination renames
        Value.Destination.S3_Bucket;
   begin
      XML_Writers.Initialize (Item, Limits);
      XML_Writers.Start_Document (Item, Root_Name, Namespace_URI);
      XML_Writers.Start_Element (Item, "Destination");
      XML_Writers.Start_Element (Item, "S3BucketDestination");
      if S3_Destination.Account_ID.Is_Set then
         XML_Writers.Text_Element
           (Item, "AccountId", US.To_String (S3_Destination.Account_ID.Value));
      end if;
      XML_Writers.Text_Element
        (Item, "Bucket", US.To_String (S3_Destination.Bucket));
      XML_Writers.Text_Element
        (Item, "Format", Inventory_Format_Image (S3_Destination.Format));
      if S3_Destination.Prefix.Is_Set then
         XML_Writers.Text_Element
           (Item, "Prefix", US.To_String (S3_Destination.Prefix.Value));
      end if;
      if S3_Destination.Encryption.Is_Set then
         XML_Writers.Start_Element (Item, "Encryption");
         if S3_Destination.Encryption.SSE_S3 then
            XML_Writers.Empty_Element (Item, "SSE-S3");
         end if;
         if S3_Destination.Encryption.SSE_KMS_Key_ID.Is_Set then
            XML_Writers.Start_Element (Item, "SSE-KMS");
            XML_Writers.Text_Element
              (Item, "KeyId",
               US.To_String (S3_Destination.Encryption.SSE_KMS_Key_ID.Value));
            XML_Writers.End_Element (Item, "SSE-KMS");
         end if;
         XML_Writers.End_Element (Item, "Encryption");
      end if;
      XML_Writers.End_Element (Item, "S3BucketDestination");
      XML_Writers.End_Element (Item, "Destination");
      XML_Writers.Text_Element
        (Item, "IsEnabled", (if Value.Is_Enabled then "true" else "false"));
      if Value.Filter.Is_Set then
         XML_Writers.Start_Element (Item, "Filter");
         XML_Writers.Text_Element
           (Item, "Prefix", US.To_String (Value.Filter.Prefix));
         XML_Writers.End_Element (Item, "Filter");
      end if;
      XML_Writers.Text_Element (Item, "Id", US.To_String (Value.ID));
      XML_Writers.Text_Element
        (Item, "IncludedObjectVersions", Versions_Image (Value.Versions));
      if not Value.Optional_Fields.Is_Empty then
         XML_Writers.Start_Element (Item, "OptionalFields");
         for Field of Value.Optional_Fields loop
            XML_Writers.Text_Element
              (Item, "Field", Optional_Field_Image (Field));
         end loop;
         XML_Writers.End_Element (Item, "OptionalFields");
      end if;
      XML_Writers.Start_Element (Item, "Schedule");
      XML_Writers.Text_Element
        (Item, "Frequency", Frequency_Image (Value.Schedule.Frequency));
      XML_Writers.End_Element (Item, "Schedule");
      return XML_Writers.Finish (Item, Root_Name);
   exception
      when XML_Writers.Encoding_Error =>
         raise Inventory.Malformed_Inventory with
           "inventory serialization violates caller limits";
   end Serialize;""",
    ),
    "PutBucketLogging": Mutation_Serializer(
        payload_shape="BucketLoggingStatus",
        value_unit="Logging",
        value_type="Logging_Status",
        closure_sha256=(
            "fbfafa4aedc36468b290b7b3172f04448e91a474c8c10b475f444e32b109fa8d"
        ),
        body="""   function Grantee_Type_Image
     (Value : ACL.Grantee_Type) return String is
     (case Value is
         when ACL.Canonical_User => "CanonicalUser",
         when ACL.Amazon_Customer_By_Email => "AmazonCustomerByEmail",
         when ACL.Group_Grantee => "Group");

   function Permission_Image
     (Value : Logging.Logging_Permission) return String is
     (case Value is
         when Logging.Full_Control => "FULL_CONTROL",
         when Logging.Read         => "READ",
         when Logging.Write        => "WRITE");

   function Date_Source_Image
     (Value : Logging.Partition_Date_Source) return String is
     (case Value is
         when Logging.Event_Time    => "EventTime",
         when Logging.Delivery_Time => "DeliveryTime");

   procedure Write_Optional_String
     (Item  : in out XML_Writers.Writer;
      Name  : String;
      Value : ACL.Optional_String) is
   begin
      if Value.Is_Set then
         XML_Writers.Text_Element (Item, Name, US.To_String (Value.Value));
      end if;
   end Write_Optional_String;

   procedure Write_Grantee
     (Item  : in out XML_Writers.Writer;
      Value : ACL.Grantee) is
   begin
      if not Value.Is_Set then
         return;
      end if;
      XML_Writers.Start_Element (Item, "Grantee");
      XML_Writers.Attribute
        (Item, "type", Grantee_Type_Image (Value.Kind),
         "http://www.w3.org/2001/XMLSchema-instance", "xsi");
      Write_Optional_String (Item, "DisplayName", Value.Display_Name);
      Write_Optional_String (Item, "EmailAddress", Value.Email_Address);
      Write_Optional_String (Item, "ID", Value.ID);
      Write_Optional_String (Item, "URI", Value.URI);
      XML_Writers.End_Element (Item, "Grantee");
   end Write_Grantee;

   function Serialize
     (Value  : Logging.Logging_Status;
      Limits : XML.Parse_Limits) return String
   is
      Item : XML_Writers.Writer;
   begin
      XML_Writers.Initialize (Item, Limits);
      XML_Writers.Start_Document (Item, Root_Name, Namespace_URI);
      if Value.Is_Enabled then
         XML_Writers.Start_Element (Item, "LoggingEnabled");
         XML_Writers.Text_Element
           (Item, "TargetBucket", US.To_String (Value.Target_Bucket));
         if Value.Grants.Is_Set then
            XML_Writers.Start_Element (Item, "TargetGrants");
            for Grant of Value.Grants.Grants loop
               XML_Writers.Start_Element (Item, "Grant");
               Write_Grantee (Item, Grant.Principal);
               if Grant.Permission.Is_Set then
                  XML_Writers.Text_Element
                    (Item, "Permission",
                     Permission_Image (Grant.Permission.Value));
               end if;
               XML_Writers.End_Element (Item, "Grant");
            end loop;
            XML_Writers.End_Element (Item, "TargetGrants");
         end if;
         XML_Writers.Text_Element
           (Item, "TargetPrefix", US.To_String (Value.Target_Prefix));
         if Value.Key_Format.Is_Set then
            XML_Writers.Start_Element (Item, "TargetObjectKeyFormat");
            if Value.Key_Format.Simple_Prefix then
               XML_Writers.Empty_Element (Item, "SimplePrefix");
            end if;
            if Value.Key_Format.Partitioned_Prefix then
               XML_Writers.Start_Element (Item, "PartitionedPrefix");
               if Value.Key_Format.Date_Source.Is_Set then
                  XML_Writers.Text_Element
                    (Item, "PartitionDateSource",
                     Date_Source_Image (Value.Key_Format.Date_Source.Value));
               end if;
               XML_Writers.End_Element (Item, "PartitionedPrefix");
            end if;
            XML_Writers.End_Element (Item, "TargetObjectKeyFormat");
         end if;
         XML_Writers.End_Element (Item, "LoggingEnabled");
      end if;
      return XML_Writers.Finish (Item, Root_Name);
   exception
      when XML_Writers.Encoding_Error =>
         raise Logging.Malformed_Logging with
           "logging serialization violates caller limits";
   end Serialize;""",
    ),
    "PutBucketWebsite": Mutation_Serializer(
        payload_shape="WebsiteConfiguration",
        value_unit="Website",
        value_type="Website_Configuration",
        closure_sha256=(
            "b1fa4a9883e1c3f4d4d8b059a5a681b4784903a9c754758ac1dc2c8f010e1fa3"
        ),
        body="""   function Protocol_Image
     (Value : Website.Protocol) return String is
     (case Value is
         when Website.HTTP  => "http",
         when Website.HTTPS => "https");

   procedure Write_Optional_String
     (Item  : in out XML_Writers.Writer;
      Name  : String;
      Value : Website.Optional_String) is
   begin
      if Value.Is_Set then
         XML_Writers.Text_Element (Item, Name, US.To_String (Value.Value));
      end if;
   end Write_Optional_String;

   procedure Write_Optional_Protocol
     (Item  : in out XML_Writers.Writer;
      Name  : String;
      Value : Website.Optional_Protocol) is
   begin
      if Value.Is_Set then
         XML_Writers.Text_Element (Item, Name, Protocol_Image (Value.Value));
      end if;
   end Write_Optional_Protocol;

   function Serialize
     (Value  : Website.Website_Configuration;
      Limits : XML.Parse_Limits) return String
   is
      Item : XML_Writers.Writer;
   begin
      if Value.Error.Is_Set and then US.Length (Value.Error.Key) = 0 then
         raise Website.Malformed_Website with
           "website ErrorDocument Key is required and nonempty";
      end if;
      XML_Writers.Initialize (Item, Limits);
      XML_Writers.Start_Document (Item, Root_Name, Namespace_URI);
      if Value.Error.Is_Set then
         XML_Writers.Start_Element (Item, "ErrorDocument");
         XML_Writers.Text_Element
           (Item, "Key", US.To_String (Value.Error.Key));
         XML_Writers.End_Element (Item, "ErrorDocument");
      end if;
      if Value.Index.Is_Set then
         XML_Writers.Start_Element (Item, "IndexDocument");
         XML_Writers.Text_Element
           (Item, "Suffix", US.To_String (Value.Index.Suffix));
         XML_Writers.End_Element (Item, "IndexDocument");
      end if;
      if Value.Redirect_All.Is_Set then
         XML_Writers.Start_Element (Item, "RedirectAllRequestsTo");
         XML_Writers.Text_Element
           (Item, "HostName", US.To_String (Value.Redirect_All.Host_Name));
         Write_Optional_Protocol
           (Item, "Protocol", Value.Redirect_All.Scheme);
         XML_Writers.End_Element (Item, "RedirectAllRequestsTo");
      end if;
      if Value.Routes.Is_Set then
         XML_Writers.Start_Element (Item, "RoutingRules");
         for Rule of Value.Routes.Rules loop
            XML_Writers.Start_Element (Item, "RoutingRule");
            if Rule.Condition.Is_Set then
               XML_Writers.Start_Element (Item, "Condition");
               Write_Optional_String
                 (Item, "HttpErrorCodeReturnedEquals",
                  Rule.Condition.HTTP_Error_Code);
               Write_Optional_String
                 (Item, "KeyPrefixEquals", Rule.Condition.Key_Prefix);
               XML_Writers.End_Element (Item, "Condition");
            end if;
            XML_Writers.Start_Element (Item, "Redirect");
            Write_Optional_String
              (Item, "HostName", Rule.Redirect.Host_Name);
            Write_Optional_String
              (Item, "HttpRedirectCode",
               Rule.Redirect.HTTP_Redirect_Code);
            Write_Optional_Protocol
              (Item, "Protocol", Rule.Redirect.Scheme);
            Write_Optional_String
              (Item, "ReplaceKeyPrefixWith",
               Rule.Redirect.Replace_Key_Prefix);
            Write_Optional_String
              (Item, "ReplaceKeyWith", Rule.Redirect.Replace_Key);
            XML_Writers.End_Element (Item, "Redirect");
            XML_Writers.End_Element (Item, "RoutingRule");
         end loop;
         XML_Writers.End_Element (Item, "RoutingRules");
      end if;
      return XML_Writers.Finish (Item, Root_Name);
   exception
      when XML_Writers.Encoding_Error =>
         raise Website.Malformed_Website with
           "website serialization violates caller limits";
   end Serialize;""",
    ),
}


def mutation_serializer_text(
    model: dict[str, Any], operation_name: str
) -> tuple[str, str, str]:
    """Generate a bounded request serializer after exact model verification."""
    descriptor = MUTATION_SERIALIZERS[operation_name]
    operation = model["operations"][operation_name]
    input_shape = model["shapes"][operation["input"]["shape"]]
    payload_member = input_shape.get("payload")
    payload = input_shape.get("members", {}).get(payload_member, {})
    namespace = payload.get("xmlNamespace", {}).get("uri", "")
    audit = s3_operation.operation_audit(model, operation_name)
    closure_sha256 = hashlib.sha256(
        json.dumps(
            audit["shapes"], sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
    ).hexdigest()
    if (
        operation.get("http", {}).get("method") != "PUT"
        or audit["response_status"] != 200
        or payload_member is None
        or payload.get("shape") != descriptor.payload_shape
        or namespace != "http://s3.amazonaws.com/doc/2006-03-01/"
        or closure_sha256 != descriptor.closure_sha256
    ):
        raise s3_operation.Audit_Error(
            f"generated mutation serializer contract changed: {operation_name}"
        )
    root_name = payload.get("locationName", descriptor.payload_shape)
    unit = (
        "flyology-object_storage-s3-generated_"
        + re.sub(r"(?<!^)(?=[A-Z])", "_", operation_name).lower()
        + "_xml"
    )
    child = "Generated_" + re.sub(
        r"(?<!^)(?=[A-Z])", "_", operation_name
    ) + "_XML"
    package = "Flyology.Object_Storage.S3." + child
    value_package = "Flyology.Object_Storage.S3." + descriptor.value_unit
    spec = f'''with {value_package};
with Flyology.Object_Storage.S3.XML;

--  Generated by tools/s3-operation.py; do not edit.
--  Exact bounded request serializer for {operation_name}.
package {package} is

   function Serialize
     (Value  : {value_package}.{descriptor.value_type};
      Limits : Flyology.Object_Storage.S3.XML.Parse_Limits) return String;

end {package};
'''
    extra_context = (
        "with Flyology.Object_Storage.S3.ACL;\n"
        if operation_name == "PutBucketLogging"
        else ""
    )
    aliases = f'''   package US renames Ada.Strings.Unbounded;
   package XML renames Flyology.Object_Storage.S3.XML;
   package XML_Writers renames Flyology.Object_Storage.S3.XML_Writers;
   package {descriptor.value_unit} renames {value_package};
'''
    if operation_name == "PutBucketLogging":
        aliases += (
            "   package ACL renames Flyology.Object_Storage.S3.ACL;\n"
        )
    body = f'''with Ada.Strings.Unbounded;
{extra_context}with Flyology.Object_Storage.S3.XML_Writers;

package body {package} is

{aliases}
   --  These values are owned by the pinned Botocore payload declaration;
   --  changing either changes the serialized and signed request contract.
   Root_Name : constant String := "{root_name}";
   Namespace_URI : constant String := "{namespace}";

{descriptor.body}

end {package};
'''
    return unit, spec, body


def generated_ada_outputs(
    registry: s3_operation.Registry,
    model: dict[str, Any],
) -> dict[Path, str]:
    """Materialize new-operation Ada while preserving handwritten peers."""
    eligible = [
        name
        for name, entry in sorted(registry.operations.items())
        if entry["generator_eligible"]
    ]
    unsupported = [name for name in eligible if name != "ListDirectoryBuckets"]
    if unsupported:
        raise s3_operation.Audit_Error(
            "Ada family generation is not implemented for: "
            + ", ".join(unsupported)
        )
    outputs: dict[Path, str] = {}
    if not eligible:
        return outputs

    entry = registry.operations["ListDirectoryBuckets"]
    unit, spec, body = codec_descriptor_text(
        model, "ListDirectoryBuckets", entry
    )
    outputs[s3_operation.ROOT / "src" / f"{unit}.ads"] = spec
    outputs[s3_operation.ROOT / "src" / f"{unit}.adb"] = body

    low_spec_path = (
        s3_operation.ROOT
        / "src/flyology-object_storage-client-low_level.ads"
    )
    low_spec = low_spec_path.read_text(encoding="utf-8")
    outputs[low_spec_path] = materialize_generated_region(
        low_spec,
        "LOW_LEVEL_VISIBLE",
        _list_directory_low_level_spec(),
        "private\n",
    )

    low_body_path = (
        s3_operation.ROOT
        / "src/flyology-object_storage-client-low_level.adb"
    )
    low_body = low_body_path.read_text(encoding="utf-8")
    low_body = materialize_generated_region(
        low_body,
        "LOW_LEVEL_CONTEXT",
        "with Flyology.Object_Storage.S3."
        "Generated_List_Directory_Buckets_XML;",
        "package body Flyology.Object_Storage.Client.Low_Level is\n",
    )
    outputs[low_body_path] = materialize_generated_region(
        low_body,
        "LOW_LEVEL_BODY",
        _list_directory_low_level_body(),
        "end Flyology.Object_Storage.Client.Low_Level;\n",
    )

    provider_spec_path = (
        s3_operation.ROOT
        / "src/flyology-object_storage-client-buckets.ads"
    )
    provider_spec = provider_spec_path.read_text(encoding="utf-8")
    provider_spec = materialize_generated_region(
        provider_spec,
        "BUCKETS_CONTEXT",
        "with Flyology.Object_Storage.Client.Paginated_REST_XML_Reads;",
        "--  High-level bucket operations over a configured Flyology HTTP client.\n",
    )
    provider_spec = materialize_generated_region(
        provider_spec,
        "BUCKETS_VISIBLE",
        _list_directory_provider_spec(),
        "private\n",
    )
    outputs[provider_spec_path] = materialize_generated_region(
        provider_spec,
        "BUCKETS_PRIVATE",
        _list_directory_provider_private_spec(),
        "   --  @exclude\n   type Create_Session_Operation",
    )

    provider_body_path = (
        s3_operation.ROOT
        / "src/flyology-object_storage-client-buckets.adb"
    )
    provider_body = provider_body_path.read_text(encoding="utf-8")
    outputs[provider_body_path] = materialize_generated_region(
        provider_body,
        "BUCKETS_BODY",
        _list_directory_provider_body(),
        "end Flyology.Object_Storage.Client.Buckets;\n",
    )
    return outputs


def check_generated_ada_outputs(
    registry: s3_operation.Registry,
    model: dict[str, Any],
) -> None:
    for path, expected in generated_ada_outputs(registry, model).items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            raise s3_operation.Audit_Error(
                "generated Ada differs: "
                + str(path.relative_to(s3_operation.ROOT))
            )


def get_bucket_website_canary(
    registry: s3_operation.Registry,
    model: dict[str, Any],
    source_overrides: dict[Path, str] | None = None,
) -> dict[str, Any]:
    """Verify prospective generation against the authoritative handwritten API."""
    operation = "GetBucketWebsite"
    entry = registry.operations[operation]
    plan = codec_plan(model, operation, entry)
    audit = s3_operation.operation_audit(model, operation)
    unit, spec, body = codec_descriptor_text(model, operation, entry)
    generated_negative = s3_operation.negative_xml_cases(
        model, operation, entry["negative_xml"]
    )
    committed_negative = json.loads(
        s3_operation.NEGATIVE_XML_PATH.read_text(encoding="utf-8")
    )["operations"][operation]["cases"]
    generated_socket = json.loads(
        s3_operation.signed_socket_text(registry, model)
    )["operations"][operation]
    committed_socket = json.loads(
        s3_operation.SIGNED_SOCKET_PATH.read_text(encoding="utf-8")
    )["operations"][operation]

    source_tokens = {
        "src/flyology-object_storage-s3-website.ads": [
            "type Website_Configuration is record",
            "function Parse",
            "Malformed_Website",
        ],
        "src/flyology-object_storage-s3-website.adb": [
            node["name"] for node in plan["nodes"]
        ],
        "src/flyology-object_storage-client-low_level.adb": [
            "Prepare_Get_Bucket_Website",
            "Model.Get_Bucket_Website_Operation",
            "Decode_Get_Bucket_Website_Response",
        ],
        "src/flyology-object_storage-client-buckets.ads": [
            "type Get_Bucket_Website_Operation",
            "package Get_Bucket_Website_Reads is new",
            "function Get_Website",
            "procedure Get_Website",
            "procedure Finish",
        ],
        "src/flyology-object_storage-client-buckets.adb": [
            "Get_Bucket_Website_Reads.Start",
            "Get_Bucket_Website_Reads.Request_Cancellation",
            "Get_Bucket_Website_Reads.Finalize",
            "function Get_Website",
            "procedure Get_Website",
            "procedure Finish",
        ],
        "tests/src/s3_get_bucket_website_qualification.adb": [
            "low_level",
            "synchronous",
            "composable",
            "restart",
            "invalid_xml",
            "Buckets.Finish (Operation, Result)",
        ],
    }
    source_hashes: dict[str, str] = {}
    findings: list[str] = []
    for path_text, tokens in source_tokens.items():
        path = s3_operation.ROOT / path_text
        value = (
            source_overrides[path].encode("utf-8")
            if source_overrides is not None and path in source_overrides
            else path.read_bytes()
        )
        source_hashes[path_text] = hashlib.sha256(value).hexdigest()
        text = value.decode("utf-8")
        for token in tokens:
            if token not in text:
                findings.append(f"{path_text} lacks {token}")

    if generated_negative != committed_negative:
        findings.append("generated negative XML differs from committed evidence")
    if generated_socket != committed_socket:
        findings.append("generated signed socket plan differs from committed evidence")
    if entry["implementation_mode"] != "shared-family":
        findings.append("authoritative implementation mode changed")
    if entry["generator_eligible"]:
        findings.append("authoritative canary became generator eligible")

    return {
        "operation": operation,
        "status": "equivalent" if not findings else "findings",
        "findings": findings,
        "authoritative_implementation": {
            "mode": entry["implementation_mode"],
            "generator_eligible": entry["generator_eligible"],
            "source_sha256": source_hashes,
        },
        "model_contract": {
            "method": audit["method"],
            "uri": audit["uri"],
            "response_status": audit["response_status"],
            "input_shape": audit["input_shape"],
            "output_shape": audit["output_shape"],
            "reachable_shape_count": audit["reachable_shape_count"],
            "payload_shape": plan["payload_shape"],
            "wire_node_count": plan["node_count"],
        },
        "public_contract": {
            "provider": entry["public_provider"],
            "operation": entry["public_name"],
            "symbols": entry["ada_symbols"],
            "family": entry["family"],
        },
        "strict_xml": {
            "contract": plan["strict_contract"],
            "negative_case_count": len(generated_negative),
            "negative_categories": dict(
                sorted(Counter(case["category"] for case in generated_negative).items())
            ),
            "unsupported_generator_traits": plan[
                "unsupported_generator_traits"
            ],
        },
        "signed_socket": {
            "case_count": len(generated_socket["cases"]),
            "lanes": [case["lane"] for case in generated_socket["cases"]],
        },
        "prospective_output": {
            "unit": unit,
            "spec_lines": len(spec.splitlines()),
            "body_lines": len(body.splitlines()),
            "spec_sha256": hashlib.sha256(spec.encode()).hexdigest(),
            "body_sha256": hashlib.sha256(body.encode()).hexdigest(),
            "committed": False,
        },
        "intentional_human_rules": entry["exclusions"],
        "coverage": entry["coverage"],
        "evidence": entry["evidence"],
    }
