with Flyology.Object_Storage.S3.XML;
with Flyology.Object_Storage.S3.Buckets;

--  Generated by tools/s3-operation.py; do not edit.
--  Operation: ListDirectoryBuckets
--  Botocore revision: 36c34f15391da01cd717c73c0fffa747c9889768
--  Model SHA-256:
--    429763d64912af5edae4c7a0f20a8ac3e6fecf734cde5fc465016bc8badcdef9
pragma Style_Checks (Off);
package Flyology.Object_Storage.S3.Generated_List_Directory_Buckets_XML is

   type Element_Id is
     (No_Element,
      Root,
      Root_Buckets,
      Root_Buckets_Item,
      Root_Buckets_Item_Name,
      Root_Buckets_Item_Creation_Date,
      Root_Buckets_Item_Bucket_Region,
      Root_Buckets_Item_Bucket_Arn,
      Root_Continuation_Token);

   Root_Element : constant Element_Id := Root;

   function Element_Name (Element : Element_Id) return String;
   function Parent (Element : Element_Id) return Element_Id;
   function Is_Scalar (Element : Element_Id) return Boolean;
   function Is_Attribute (Element : Element_Id) return Boolean;
   function Attribute_Namespace
     (Element : Element_Id) return String;
   function Is_Repeated (Element : Element_Id) return Boolean;
   function Is_Required (Element : Element_Id) return Boolean;
   function Is_Boolean (Element : Element_Id) return Boolean;
   function Is_Integer (Element : Element_Id) return Boolean;
   function Is_Timestamp (Element : Element_Id) return Boolean;
   function Minimum_Length (Element : Element_Id) return Natural;
   function Has_Maximum_Length
     (Element : Element_Id) return Boolean;
   function Maximum_Length (Element : Element_Id) return Natural;
   function Enumeration_Count (Element : Element_Id) return Natural;
   function Enumeration_Value
     (Element : Element_Id; Index : Positive) return String;
   function Matches_Pattern
     (Element : Element_Id; Value : String) return Boolean;

   generic
      type Result_Type is limited private;
      with procedure Start_Node
        (Result : in out Result_Type; Element : Element_Id);
      with procedure Set_Scalar
        (Result : in out Result_Type; Element : Element_Id;
         Value : String);
      with procedure End_Node
        (Result : in out Result_Type; Element : Element_Id);
   package Decoder is
      Malformed_Document : exception;
      procedure Parse
        (Document         : String;
         Limits           : XML.Parse_Limits;
         Collection_Limit : Positive;
         Result           : aliased in out Result_Type);
   end Decoder;

   Malformed_Document : exception;

   function Parse
     (Document         : String;
      Limits           : XML.Parse_Limits;
      Collection_Limit : Positive)
      return Flyology.Object_Storage.S3.Buckets.List_Buckets_Result;

end Flyology.Object_Storage.S3.Generated_List_Directory_Buckets_XML;
