with Flyology.Object_Storage.S3.Strict_XML_Codecs;
with Ada.Strings.Unbounded;

--  Generated by tools/s3-operation.py; do not edit.
--  Operation: ListDirectoryBuckets
pragma Style_Checks (Off);
package body Flyology.Object_Storage.S3.Generated_List_Directory_Buckets_XML is

   function Element_Name (Element : Element_Id) return String is
   begin
      case Element is
         when Root =>
            return "ListDirectoryBucketsOutput";
         when Root_Buckets =>
            return "Buckets";
         when Root_Buckets_Item =>
            return "Bucket";
         when Root_Buckets_Item_Name =>
            return "Name";
         when Root_Buckets_Item_Creation_Date =>
            return "CreationDate";
         when Root_Buckets_Item_Bucket_Region =>
            return "BucketRegion";
         when Root_Buckets_Item_Bucket_Arn =>
            return "BucketArn";
         when Root_Continuation_Token =>
            return "ContinuationToken";
         when others =>
            return "";
      end case;
   end Element_Name;

   function Parent (Element : Element_Id) return Element_Id is
   begin
      case Element is
         when Root =>
            return No_Element;
         when Root_Buckets =>
            return Root;
         when Root_Buckets_Item =>
            return Root_Buckets;
         when Root_Buckets_Item_Name =>
            return Root_Buckets_Item;
         when Root_Buckets_Item_Creation_Date =>
            return Root_Buckets_Item;
         when Root_Buckets_Item_Bucket_Region =>
            return Root_Buckets_Item;
         when Root_Buckets_Item_Bucket_Arn =>
            return Root_Buckets_Item;
         when Root_Continuation_Token =>
            return Root;
         when No_Element =>
            return No_Element;
      end case;
   end Parent;

   function Is_Scalar (Element : Element_Id) return Boolean is
     (Element in Root_Buckets_Item_Name | Root_Buckets_Item_Creation_Date | Root_Buckets_Item_Bucket_Region | Root_Buckets_Item_Bucket_Arn | Root_Continuation_Token);

   function Is_Attribute (Element : Element_Id) return Boolean is
     (False);

   function Is_Repeated (Element : Element_Id) return Boolean is
     (Element in Root_Buckets_Item);

   function Is_Required (Element : Element_Id) return Boolean is
     (False);

   function Is_Boolean (Element : Element_Id) return Boolean is
     (False);

   function Is_Integer (Element : Element_Id) return Boolean is
     (False);

   function Is_Timestamp (Element : Element_Id) return Boolean is
     (Element in Root_Buckets_Item_Creation_Date);

   function Has_Maximum_Length (Element : Element_Id) return Boolean is
     (Element in Root_Buckets_Item_Bucket_Arn | Root_Continuation_Token);

   function Attribute_Namespace (Element : Element_Id) return String is
   begin
      case Element is
         when others =>
            return "";
      end case;
   end Attribute_Namespace;

   function Minimum_Length
     (Element : Element_Id) return Natural is
   begin
      case Element is
         when Root_Buckets_Item_Bucket_Arn =>
            return 1;
         when others =>
            return 0;
      end case;
   end Minimum_Length;

   function Maximum_Length
     (Element : Element_Id) return Natural is
   begin
      case Element is
         when Root_Buckets_Item_Bucket_Arn =>
            return 128;
         when Root_Continuation_Token =>
            return 1024;
         when others =>
            return 0;
      end case;
   end Maximum_Length;

   function Enumeration_Count
     (Element : Element_Id) return Natural is
   begin
      case Element is
         when others =>
            return 0;
      end case;
   end Enumeration_Count;

   function Enumeration_Value
     (Element : Element_Id; Index : Positive) return String is
      pragma Unreferenced (Element, Index);
   begin
      return (raise Constraint_Error);
   end Enumeration_Value;

   function Matches_S3_Bucket_ARN
     (Value : String) return Boolean is
      Service_Start : Integer;
      Separator     : Integer;
   begin
      if Value'Length < 8
        or else Value (Value'First .. Value'First + 3) /= "arn:"
      then
         return False;
      end if;
      Service_Start := Value'First + 4;
      Separator := Service_Start;
      while Separator <= Value'Last
        and then Value (Separator) /= ':'
      loop
         Separator := Separator + 1;
      end loop;
      if Separator = Service_Start or else Separator > Value'Last then
         return False;
      end if;
      Service_Start := Separator + 1;
      return
        (Service_Start + 2 <= Value'Last
         and then Value (Service_Start .. Service_Start + 2) = "s3:")
        or else
        (Service_Start + 9 <= Value'Last
         and then Value (Service_Start .. Service_Start + 9) =
           "s3express:");
   end Matches_S3_Bucket_ARN;

   function Matches_Pattern
     (Element : Element_Id; Value : String) return Boolean is
   begin
      case Element is
         when Root_Buckets_Item_Bucket_Arn =>
            return Matches_S3_Bucket_ARN (Value);
         when others =>
            return True;
      end case;
   end Matches_Pattern;

   package body Decoder is
      package Runtime is new
        Flyology.Object_Storage.S3.Strict_XML_Codecs
        (Element_Id          => Element_Id,
         No_Element         => No_Element,
         Root_Element       => Root_Element,
         Element_Name       => Element_Name,
         Parent             => Parent,
         Is_Scalar          => Is_Scalar,
         Is_Attribute       => Is_Attribute,
         Attribute_Namespace => Attribute_Namespace,
         Is_Repeated        => Is_Repeated,
         Is_Required        => Is_Required,
         Is_Boolean         => Is_Boolean,
         Is_Integer         => Is_Integer,
         Is_Timestamp       => Is_Timestamp,
         Minimum_Length     => Minimum_Length,
         Has_Maximum_Length => Has_Maximum_Length,
         Maximum_Length     => Maximum_Length,
         Enumeration_Count  => Enumeration_Count,
         Enumeration_Value  => Enumeration_Value,
         Matches_Pattern    => Matches_Pattern,
         Result_Type        => Result_Type,
         Start_Node         => Start_Node,
         Set_Scalar         => Set_Scalar,
         End_Node           => End_Node);

      procedure Parse
        (Document         : String;
         Limits           : XML.Parse_Limits;
         Collection_Limit : Positive;
         Result           : aliased in out Result_Type) is
      begin
         Runtime.Parse
           (Document, Limits, Collection_Limit, Result);
      exception
         when Runtime.Malformed_Document =>
            raise Malformed_Document;
      end Parse;
   end Decoder;

   package US renames Ada.Strings.Unbounded;

   type Parse_State is record
      Value   : Flyology.Object_Storage.S3.Buckets.List_Buckets_Result;
      Current : Flyology.Object_Storage.S3.Buckets.Bucket_Entry;
   end record;

   procedure Start_Node
     (Result : in out Parse_State; Element : Element_Id) is
   begin
      if Element = Root_Buckets_Item then
         Result.Current := (others => <>);
      end if;
   end Start_Node;

   procedure Set_Scalar
     (Result  : in out Parse_State;
      Element : Element_Id;
      Value   : String) is
   begin
      case Element is
         when Root_Buckets_Item_Name =>
            Result.Current.Name := US.To_Unbounded_String (Value);
         when Root_Buckets_Item_Creation_Date =>
            Result.Current.Creation_Date := US.To_Unbounded_String (Value);
         when Root_Buckets_Item_Bucket_Region =>
            Result.Current.Bucket_Region := US.To_Unbounded_String (Value);
         when Root_Buckets_Item_Bucket_Arn =>
            Result.Current.Bucket_ARN := US.To_Unbounded_String (Value);
         when Root_Continuation_Token =>
            Result.Value.Continuation_Token := US.To_Unbounded_String (Value);
            Result.Value.Has_Continuation_Token := True;
         when others =>
            null;
      end case;
   end Set_Scalar;

   procedure End_Node
     (Result : in out Parse_State; Element : Element_Id) is
   begin
      if Element = Root_Buckets_Item then
         Result.Value.Buckets.Append (Result.Current);
      end if;
   end End_Node;

   package Typed_Decoder is new Decoder
     (Result_Type => Parse_State,
      Start_Node  => Start_Node,
      Set_Scalar  => Set_Scalar,
      End_Node    => End_Node);

   function Parse
     (Document         : String;
      Limits           : XML.Parse_Limits;
      Collection_Limit : Positive)
      return Flyology.Object_Storage.S3.Buckets.List_Buckets_Result
   is
      State : aliased Parse_State;
   begin
      Typed_Decoder.Parse (Document, Limits, Collection_Limit, State);
      return State.Value;
   exception
      when Typed_Decoder.Malformed_Document =>
         raise Malformed_Document;
   end Parse;

end Flyology.Object_Storage.S3.Generated_List_Directory_Buckets_XML;
