--  Generated by tools/generate-s3-model.py; do not edit.
--  Source: pinned botocore service-2.json recorded below.
pragma Style_Checks (Off);

--  Pinned S3 REST/XML service-model descriptor.
package Flyology.Object_Storage.S3.Model
  with SPARK_Mode => On
is

   --  SHA-256 digest of the pinned service model.
   Model_SHA256 : constant String := "429763d64912af5edae4c7a0f20a8ac3e6fecf734cde5fc465016bc8badcdef9";
   --  Number of operations in the pinned service model.
   Operation_Count : constant := 116;
   --  Number of shapes in the pinned service model.
   Shape_Count : constant := 718;

   --  Identifiers for operations in the pinned S3 model.
   --  @enum Abort_Multipart_Upload_Operation
   --    Pinned S3 operation AbortMultipartUpload
   --  @enum Complete_Multipart_Upload_Operation
   --    Pinned S3 operation CompleteMultipartUpload
   --  @enum Copy_Object_Operation Pinned S3 operation CopyObject
   --  @enum Create_Bucket_Operation Pinned S3 operation CreateBucket
   --  @enum Create_Bucket_Metadata_Configuration_Operation
   --    Pinned S3 operation CreateBucketMetadataConfiguration
   --  @enum Create_Bucket_Metadata_Table_Configuration_Operation
   --    Create metadata-table configuration
   --  @enum Create_Multipart_Upload_Operation
   --    Pinned S3 operation CreateMultipartUpload
   --  @enum Create_Session_Operation
   --    Create directory-bucket session credentials
   --  @enum Delete_Bucket_Operation Pinned S3 operation DeleteBucket
   --  @enum Delete_Bucket_Analytics_Configuration_Operation Delete analytics
   --  @enum Delete_Bucket_Cors_Operation Delete bucket CORS operation
   --  @enum Delete_Bucket_Encryption_Operation Delete bucket encryption
   --  @enum Delete_Bucket_Intelligent_Tiering_Configuration_Operation
   --    Delete intelligent-tiering configuration
   --  @enum Delete_Bucket_Inventory_Configuration_Operation
   --    Delete inventory configuration
   --  @enum Delete_Bucket_Lifecycle_Operation Delete bucket lifecycle
   --  @enum Delete_Bucket_Metadata_Configuration_Operation
   --    Delete metadata configuration
   --  @enum Delete_Bucket_Metadata_Table_Configuration_Operation
   --    Delete metadata-table configuration
   --  @enum Delete_Bucket_Metrics_Configuration_Operation
   --    Delete metrics configuration
   --  @enum Delete_Bucket_Ownership_Controls_Operation
   --    Delete bucket ownership controls
   --  @enum Delete_Bucket_Policy_Operation Delete bucket policy
   --  @enum Delete_Bucket_Replication_Operation Delete bucket replication
   --  @enum Delete_Bucket_Tagging_Operation Delete bucket tagging operation
   --  @enum Delete_Bucket_Website_Operation Delete bucket website
   --  @enum Delete_Object_Operation Pinned S3 operation DeleteObject
   --  @enum Delete_Object_Annotation_Operation
   --    Pinned S3 operation DeleteObjectAnnotation
   --  @enum Delete_Object_Tagging_Operation
   --    Pinned S3 operation DeleteObjectTagging
   --  @enum Delete_Objects_Operation Pinned S3 operation DeleteObjects
   --  @enum Delete_Public_Access_Block_Operation Delete public access block
   --  @enum Get_Bucket_Abac_Operation Pinned S3 operation GetBucketAbac
   --  @enum Get_Bucket_Accelerate_Configuration_Operation
   --    Pinned S3 operation GetBucketAccelerateConfiguration
   --  @enum Get_Bucket_Acl_Operation Pinned S3 operation GetBucketAcl
   --  @enum Get_Bucket_Analytics_Configuration_Operation
   --    Pinned S3 operation GetBucketAnalyticsConfiguration
   --  @enum Get_Bucket_Cors_Operation Get bucket CORS operation
   --  @enum Get_Bucket_Encryption_Operation
   --    Pinned S3 operation GetBucketEncryption
   --  @enum Get_Bucket_Intelligent_Tiering_Configuration_Operation
   --    Pinned S3 operation GetBucketIntelligentTieringConfiguration
   --  @enum Get_Bucket_Inventory_Configuration_Operation
   --    Pinned S3 operation GetBucketInventoryConfiguration
   --  @enum Get_Bucket_Lifecycle_Operation
   --    Pinned S3 operation GetBucketLifecycle
   --  @enum Get_Bucket_Lifecycle_Configuration_Operation
   --    Pinned S3 operation GetBucketLifecycleConfiguration
   --  @enum Get_Bucket_Location_Operation
   --    Pinned S3 operation GetBucketLocation
   --  @enum Get_Bucket_Logging_Operation Pinned S3 operation GetBucketLogging
   --  @enum Get_Bucket_Metadata_Configuration_Operation
   --    Pinned S3 operation GetBucketMetadataConfiguration
   --  @enum Get_Bucket_Metadata_Table_Configuration_Operation
   --    Pinned S3 operation GetBucketMetadataTableConfiguration
   --  @enum Get_Bucket_Metrics_Configuration_Operation
   --    Pinned S3 operation GetBucketMetricsConfiguration
   --  @enum Get_Bucket_Notification_Operation
   --    Pinned S3 operation GetBucketNotification
   --  @enum Get_Bucket_Notification_Configuration_Operation
   --    Pinned S3 operation GetBucketNotificationConfiguration
   --  @enum Get_Bucket_Ownership_Controls_Operation
   --    Pinned S3 operation GetBucketOwnershipControls
   --  @enum Get_Bucket_Policy_Operation Get bucket policy
   --  @enum Get_Bucket_Policy_Status_Operation
   --    Pinned S3 operation GetBucketPolicyStatus
   --  @enum Get_Bucket_Replication_Operation
   --    Pinned S3 operation GetBucketReplication
   --  @enum Get_Bucket_Request_Payment_Operation
   --    Pinned S3 operation GetBucketRequestPayment
   --  @enum Get_Bucket_Tagging_Operation Get bucket tagging operation
   --  @enum Get_Bucket_Versioning_Operation
   --    Pinned S3 operation GetBucketVersioning
   --  @enum Get_Bucket_Website_Operation Pinned S3 operation GetBucketWebsite
   --  @enum Get_Object_Operation Pinned S3 operation GetObject
   --  @enum Get_Object_Acl_Operation Pinned S3 operation GetObjectAcl
   --  @enum Get_Object_Annotation_Operation
   --    Pinned S3 operation GetObjectAnnotation
   --  @enum Get_Object_Attributes_Operation Get object attributes operation
   --  @enum Get_Object_Legal_Hold_Operation
   --    Pinned S3 operation GetObjectLegalHold
   --  @enum Get_Object_Lock_Configuration_Operation
   --    Pinned S3 operation GetObjectLockConfiguration
   --  @enum Get_Object_Retention_Operation
   --    Pinned S3 operation GetObjectRetention
   --  @enum Get_Object_Tagging_Operation Pinned S3 operation GetObjectTagging
   --  @enum Get_Object_Torrent_Operation Pinned S3 operation GetObjectTorrent
   --  @enum Get_Public_Access_Block_Operation Get public access block
   --  @enum Head_Bucket_Operation Pinned S3 operation HeadBucket
   --  @enum Head_Object_Operation Pinned S3 operation HeadObject
   --  @enum List_Bucket_Analytics_Configurations_Operation
   --    Pinned S3 operation ListBucketAnalyticsConfigurations
   --  @enum List_Bucket_Intelligent_Tiering_Configurations_Operation
   --    Pinned S3 operation ListBucketIntelligentTieringConfigurations
   --  @enum List_Bucket_Inventory_Configurations_Operation
   --    Pinned S3 operation ListBucketInventoryConfigurations
   --  @enum List_Bucket_Metrics_Configurations_Operation
   --    Pinned S3 operation ListBucketMetricsConfigurations
   --  @enum List_Buckets_Operation Pinned S3 operation ListBuckets
   --  @enum List_Directory_Buckets_Operation
   --    Pinned S3 operation ListDirectoryBuckets
   --  @enum List_Multipart_Uploads_Operation
   --    Pinned S3 operation ListMultipartUploads
   --  @enum List_Object_Annotations_Operation
   --    Pinned S3 operation ListObjectAnnotations
   --  @enum List_Object_Versions_Operation
   --    Pinned S3 operation ListObjectVersions
   --  @enum List_Objects_Operation Pinned S3 operation ListObjects
   --  @enum List_Objects_V2_Operation Pinned S3 operation ListObjectsV2
   --  @enum List_Parts_Operation List multipart upload parts
   --  @enum Put_Bucket_Abac_Operation Pinned S3 operation PutBucketAbac
   --  @enum Put_Bucket_Accelerate_Configuration_Operation
   --    Pinned S3 operation PutBucketAccelerateConfiguration
   --  @enum Put_Bucket_Acl_Operation Pinned S3 operation PutBucketAcl
   --  @enum Put_Bucket_Analytics_Configuration_Operation
   --    Pinned S3 operation PutBucketAnalyticsConfiguration
   --  @enum Put_Bucket_Cors_Operation Put bucket CORS operation
   --  @enum Put_Bucket_Encryption_Operation
   --    Pinned S3 operation PutBucketEncryption
   --  @enum Put_Bucket_Intelligent_Tiering_Configuration_Operation
   --    Pinned S3 operation PutBucketIntelligentTieringConfiguration
   --  @enum Put_Bucket_Inventory_Configuration_Operation
   --    Pinned S3 operation PutBucketInventoryConfiguration
   --  @enum Put_Bucket_Lifecycle_Operation
   --    Pinned S3 operation PutBucketLifecycle
   --  @enum Put_Bucket_Lifecycle_Configuration_Operation
   --    Pinned S3 operation PutBucketLifecycleConfiguration
   --  @enum Put_Bucket_Logging_Operation Pinned S3 operation PutBucketLogging
   --  @enum Put_Bucket_Metrics_Configuration_Operation
   --    Pinned S3 operation PutBucketMetricsConfiguration
   --  @enum Put_Bucket_Notification_Operation
   --    Pinned S3 operation PutBucketNotification
   --  @enum Put_Bucket_Notification_Configuration_Operation
   --    Pinned S3 operation PutBucketNotificationConfiguration
   --  @enum Put_Bucket_Ownership_Controls_Operation
   --    Pinned S3 operation PutBucketOwnershipControls
   --  @enum Put_Bucket_Policy_Operation Put bucket policy
   --  @enum Put_Bucket_Replication_Operation
   --    Pinned S3 operation PutBucketReplication
   --  @enum Put_Bucket_Request_Payment_Operation
   --    Pinned S3 operation PutBucketRequestPayment
   --  @enum Put_Bucket_Tagging_Operation Put bucket tagging operation
   --  @enum Put_Bucket_Versioning_Operation
   --    Pinned S3 operation PutBucketVersioning
   --  @enum Put_Bucket_Website_Operation Pinned S3 operation PutBucketWebsite
   --  @enum Put_Object_Operation Pinned S3 operation PutObject
   --  @enum Put_Object_Acl_Operation Pinned S3 operation PutObjectAcl
   --  @enum Put_Object_Annotation_Operation
   --    Pinned S3 operation PutObjectAnnotation
   --  @enum Put_Object_Legal_Hold_Operation
   --    Pinned S3 operation PutObjectLegalHold
   --  @enum Put_Object_Lock_Configuration_Operation
   --    Pinned S3 operation PutObjectLockConfiguration
   --  @enum Put_Object_Retention_Operation
   --    Pinned S3 operation PutObjectRetention
   --  @enum Put_Object_Tagging_Operation Pinned S3 operation PutObjectTagging
   --  @enum Put_Public_Access_Block_Operation Put public access block
   --  @enum Rename_Object_Operation Pinned S3 operation RenameObject
   --  @enum Restore_Object_Operation Pinned S3 operation RestoreObject
   --  @enum Select_Object_Content_Operation
   --    Pinned S3 operation SelectObjectContent
   --  @enum Update_Bucket_Metadata_Annotation_Table_Configuration_Operation
   --    Pinned S3 operation UpdateBucketMetadataAnnotationTableConfiguration
   --  @enum Update_Bucket_Metadata_Inventory_Table_Configuration_Operation
   --    Pinned S3 operation UpdateBucketMetadataInventoryTableConfiguration
   --  @enum Update_Bucket_Metadata_Journal_Table_Configuration_Operation
   --    Pinned S3 operation UpdateBucketMetadataJournalTableConfiguration
   --  @enum Update_Object_Encryption_Operation
   --    Pinned S3 operation UpdateObjectEncryption
   --  @enum Upload_Part_Operation Upload multipart upload part
   --  @enum Upload_Part_Copy_Operation
   --    Upload multipart part from a source object
   --  @enum Write_Get_Object_Response_Operation
   --    Pinned S3 operation WriteGetObjectResponse
   type Operation_Id is
     (Abort_Multipart_Upload_Operation,
      Complete_Multipart_Upload_Operation,
      Copy_Object_Operation,
      Create_Bucket_Operation,
      Create_Bucket_Metadata_Configuration_Operation,
      Create_Bucket_Metadata_Table_Configuration_Operation,
      Create_Multipart_Upload_Operation,
      Create_Session_Operation,
      Delete_Bucket_Operation,
      Delete_Bucket_Analytics_Configuration_Operation,
      Delete_Bucket_Cors_Operation,
      Delete_Bucket_Encryption_Operation,
      Delete_Bucket_Intelligent_Tiering_Configuration_Operation,
      Delete_Bucket_Inventory_Configuration_Operation,
      Delete_Bucket_Lifecycle_Operation,
      Delete_Bucket_Metadata_Configuration_Operation,
      Delete_Bucket_Metadata_Table_Configuration_Operation,
      Delete_Bucket_Metrics_Configuration_Operation,
      Delete_Bucket_Ownership_Controls_Operation,
      Delete_Bucket_Policy_Operation,
      Delete_Bucket_Replication_Operation,
      Delete_Bucket_Tagging_Operation,
      Delete_Bucket_Website_Operation,
      Delete_Object_Operation,
      Delete_Object_Annotation_Operation,
      Delete_Object_Tagging_Operation,
      Delete_Objects_Operation,
      Delete_Public_Access_Block_Operation,
      Get_Bucket_Abac_Operation,
      Get_Bucket_Accelerate_Configuration_Operation,
      Get_Bucket_Acl_Operation,
      Get_Bucket_Analytics_Configuration_Operation,
      Get_Bucket_Cors_Operation,
      Get_Bucket_Encryption_Operation,
      Get_Bucket_Intelligent_Tiering_Configuration_Operation,
      Get_Bucket_Inventory_Configuration_Operation,
      Get_Bucket_Lifecycle_Operation,
      Get_Bucket_Lifecycle_Configuration_Operation,
      Get_Bucket_Location_Operation,
      Get_Bucket_Logging_Operation,
      Get_Bucket_Metadata_Configuration_Operation,
      Get_Bucket_Metadata_Table_Configuration_Operation,
      Get_Bucket_Metrics_Configuration_Operation,
      Get_Bucket_Notification_Operation,
      Get_Bucket_Notification_Configuration_Operation,
      Get_Bucket_Ownership_Controls_Operation,
      Get_Bucket_Policy_Operation,
      Get_Bucket_Policy_Status_Operation,
      Get_Bucket_Replication_Operation,
      Get_Bucket_Request_Payment_Operation,
      Get_Bucket_Tagging_Operation,
      Get_Bucket_Versioning_Operation,
      Get_Bucket_Website_Operation,
      Get_Object_Operation,
      Get_Object_Acl_Operation,
      Get_Object_Annotation_Operation,
      Get_Object_Attributes_Operation,
      Get_Object_Legal_Hold_Operation,
      Get_Object_Lock_Configuration_Operation,
      Get_Object_Retention_Operation,
      Get_Object_Tagging_Operation,
      Get_Object_Torrent_Operation,
      Get_Public_Access_Block_Operation,
      Head_Bucket_Operation,
      Head_Object_Operation,
      List_Bucket_Analytics_Configurations_Operation,
      List_Bucket_Intelligent_Tiering_Configurations_Operation,
      List_Bucket_Inventory_Configurations_Operation,
      List_Bucket_Metrics_Configurations_Operation,
      List_Buckets_Operation,
      List_Directory_Buckets_Operation,
      List_Multipart_Uploads_Operation,
      List_Object_Annotations_Operation,
      List_Object_Versions_Operation,
      List_Objects_Operation,
      List_Objects_V2_Operation,
      List_Parts_Operation,
      Put_Bucket_Abac_Operation,
      Put_Bucket_Accelerate_Configuration_Operation,
      Put_Bucket_Acl_Operation,
      Put_Bucket_Analytics_Configuration_Operation,
      Put_Bucket_Cors_Operation,
      Put_Bucket_Encryption_Operation,
      Put_Bucket_Intelligent_Tiering_Configuration_Operation,
      Put_Bucket_Inventory_Configuration_Operation,
      Put_Bucket_Lifecycle_Operation,
      Put_Bucket_Lifecycle_Configuration_Operation,
      Put_Bucket_Logging_Operation,
      Put_Bucket_Metrics_Configuration_Operation,
      Put_Bucket_Notification_Operation,
      Put_Bucket_Notification_Configuration_Operation,
      Put_Bucket_Ownership_Controls_Operation,
      Put_Bucket_Policy_Operation,
      Put_Bucket_Replication_Operation,
      Put_Bucket_Request_Payment_Operation,
      Put_Bucket_Tagging_Operation,
      Put_Bucket_Versioning_Operation,
      Put_Bucket_Website_Operation,
      Put_Object_Operation,
      Put_Object_Acl_Operation,
      Put_Object_Annotation_Operation,
      Put_Object_Legal_Hold_Operation,
      Put_Object_Lock_Configuration_Operation,
      Put_Object_Retention_Operation,
      Put_Object_Tagging_Operation,
      Put_Public_Access_Block_Operation,
      Rename_Object_Operation,
      Restore_Object_Operation,
      Select_Object_Content_Operation,
      Update_Bucket_Metadata_Annotation_Table_Configuration_Operation,
      Update_Bucket_Metadata_Inventory_Table_Configuration_Operation,
      Update_Bucket_Metadata_Journal_Table_Configuration_Operation,
      Update_Object_Encryption_Operation,
      Upload_Part_Operation,
      Upload_Part_Copy_Operation,
      Write_Get_Object_Response_Operation);

   --  HTTP methods used by modeled operations.
   --  @enum Delete_Method HTTP DELETE method
   --  @enum Get_Method HTTP GET method
   --  @enum Head_Method HTTP HEAD method
   --  @enum Post_Method HTTP POST method
   --  @enum Put_Method HTTP PUT method
   type HTTP_Method is
     (Delete_Method, Get_Method, Head_Method, Post_Method,
      Put_Method);

   --  Structural kinds used by modeled shapes.
   --  @enum Blob_Shape Blob shape
   --  @enum Boolean_Shape Boolean shape
   --  @enum Integer_Shape Integer shape
   --  @enum List_Shape List shape
   --  @enum Long_Shape Long-integer shape
   --  @enum Map_Shape Map shape
   --  @enum String_Shape String shape
   --  @enum Structure_Shape Structure shape
   --  @enum Timestamp_Shape Timestamp shape
   type Shape_Kind is
     (Blob_Shape, Boolean_Shape, Integer_Shape, List_Shape,
      Long_Shape, Map_Shape, String_Shape, Structure_Shape,
      Timestamp_Shape);

   --  Wire locations used by modeled structure members.
   --  @enum Body_Location Serialized body member
   --  @enum Header_Location Single HTTP header
   --  @enum Headers_Location HTTP header map
   --  @enum Query_Location URI query parameter
   --  @enum URI_Location URI path label
   type Member_Location is
     (Body_Location, Header_Location, Headers_Location,
      Query_Location, URI_Location);

   --  Optional one-based reference to a modeled shape.
   subtype Shape_Reference is Natural range 0 .. Shape_Count;
   --  One-based reference to a modeled shape.
   subtype Shape_Index is Shape_Reference range 1 .. Shape_Count;
   --  Sentinel for an absent shape reference.
   No_Shape : constant Shape_Reference := 0;

   --  Return the pinned-model operation name.
   --  @param Operation Modeled operation identifier
   --  @return Pinned service-model operation name
   function Operation_Name (Operation : Operation_Id) return String;
   --  Return the modeled HTTP method.
   --  @param Operation Modeled operation identifier
   --  @return HTTP method for the operation
   function Method (Operation : Operation_Id) return HTTP_Method;
   --  Return the modeled request URI template.
   --  @param Operation Modeled operation identifier
   --  @return Request URI template for the operation
   function Request_URI (Operation : Operation_Id) return String;
   --  Return the modeled success response status.
   --  @param Operation Modeled operation identifier
   --  @return Success response status for the operation
   function Response_Code (Operation : Operation_Id) return Positive;
   --  Return the modeled input shape.
   --  @param Operation Modeled operation identifier
   --  @return Input shape reference or No_Shape
   function Input_Shape
     (Operation : Operation_Id) return Shape_Reference;
   --  Return the modeled output shape.
   --  @param Operation Modeled operation identifier
   --  @return Output shape reference or No_Shape
   function Output_Shape
     (Operation : Operation_Id) return Shape_Reference;
   --  Return the number of modeled error shapes.
   --  @param Operation Modeled operation identifier
   --  @return Number of error shapes for the operation
   function Error_Count (Operation : Operation_Id) return Natural;
   --  Return one modeled error shape.
   --  @param Operation Modeled operation identifier
   --  @param Index One-based error-shape index
   --  @return Indexed error shape reference
   function Error_Shape
     (Operation : Operation_Id; Index : Positive)
      return Shape_Reference
   with Pre => Index <= Error_Count (Operation);
   --  Report whether the modeled payload is unsigned.
   --  @param Operation Modeled operation identifier
   --  @return True when the model selects an unsigned payload
   function Unsigned_Payload
     (Operation : Operation_Id) return Boolean;
   --  Return the modeled authentication type.
   --  @param Operation Modeled operation identifier
   --  @return Authentication type or an empty string
   function Authentication_Type
     (Operation : Operation_Id) return String;
   --  Report whether the model requires a request checksum.
   --  @param Operation Modeled operation identifier
   --  @return True when a request checksum is required
   function Request_Checksum_Required
     (Operation : Operation_Id) return Boolean;
   --  Return the modeled request-checksum algorithm member.
   --  @param Operation Modeled operation identifier
   --  @return Algorithm member name or an empty string
   function Request_Checksum_Algorithm_Member
     (Operation : Operation_Id) return String;
   --  Return the modeled request validation-mode member.
   --  @param Operation Modeled operation identifier
   --  @return Validation-mode member name or an empty string
   function Request_Validation_Mode_Member
     (Operation : Operation_Id) return String;
   --  Return the modeled response-checksum algorithms.
   --  @param Operation Modeled operation identifier
   --  @return Semicolon-separated algorithm names or an empty string
   function Response_Checksum_Algorithms
     (Operation : Operation_Id) return String;

   --  Return the pinned-model shape name.
   --  @param Shape Modeled shape index
   --  @return Pinned service-model shape name
   function Shape_Name (Shape : Shape_Index) return String;
   --  Return the modeled shape kind.
   --  @param Shape Modeled shape index
   --  @return Kind of the modeled shape
   function Kind (Shape : Shape_Index) return Shape_Kind;
   --  Return the modeled shape location name.
   --  @param Shape Modeled shape index
   --  @return Location name or an empty string
   function Location_Name (Shape : Shape_Index) return String;
   --  Return the modeled payload member name.
   --  @param Shape Modeled shape index
   --  @return Payload member name or an empty string
   function Payload_Member (Shape : Shape_Index) return String;
   --  Return the modeled timestamp format.
   --  @param Shape Modeled shape index
   --  @return Timestamp format or an empty string
   function Timestamp_Format (Shape : Shape_Index) return String;
   --  Return the modeled string pattern.
   --  @param Shape Modeled shape index
   --  @return Pattern or an empty string
   function Pattern (Shape : Shape_Index) return String;
   --  Return the modeled minimum constraint.
   --  @param Shape Modeled shape index
   --  @return Minimum image or an empty string
   function Minimum (Shape : Shape_Index) return String;
   --  Return the modeled maximum constraint.
   --  @param Shape Modeled shape index
   --  @return Maximum image or an empty string
   function Maximum (Shape : Shape_Index) return String;
   --  Report whether the modeled shape is flattened.
   --  @param Shape Modeled shape index
   --  @return True when the shape is flattened
   function Is_Flattened (Shape : Shape_Index) return Boolean;
   --  Report whether the modeled shape is sensitive.
   --  @param Shape Modeled shape index
   --  @return True when the shape is sensitive
   function Is_Sensitive (Shape : Shape_Index) return Boolean;
   --  Return the modeled XML namespace.
   --  @param Shape Modeled shape index
   --  @return Namespace URI or an empty string
   function XML_Namespace (Shape : Shape_Index) return String;
   --  Return the modeled list-member shape.
   --  @param Shape Modeled list shape index
   --  @return List-member shape reference or No_Shape
   function List_Member_Shape
     (Shape : Shape_Index) return Shape_Reference;
   --  Return the modeled map-key shape.
   --  @param Shape Modeled map shape index
   --  @return Map-key shape reference or No_Shape
   function Map_Key_Shape
     (Shape : Shape_Index) return Shape_Reference;
   --  Return the modeled map-value shape.
   --  @param Shape Modeled map shape index
   --  @return Map-value shape reference or No_Shape
   function Map_Value_Shape
     (Shape : Shape_Index) return Shape_Reference;
   --  Return the number of modeled enumeration values.
   --  @param Shape Modeled shape index
   --  @return Number of enumeration values
   function Enumeration_Count (Shape : Shape_Index) return Natural;
   --  Return one modeled enumeration value.
   --  @param Shape Modeled shape index
   --  @param Index One-based enumeration-value index
   --  @return Indexed enumeration value
   function Enumeration_Value
     (Shape : Shape_Index; Index : Positive) return String
   with Pre => Index <= Enumeration_Count (Shape);

   --  Return the number of modeled structure members.
   --  @param Shape Modeled structure shape index
   --  @return Number of modeled members
   function Member_Count (Shape : Shape_Index) return Natural;
   --  Return one modeled member name.
   --  @param Shape Modeled structure shape index
   --  @param Member One-based member index
   --  @return Indexed member name
   function Member_Name
     (Shape : Shape_Index; Member : Positive) return String
   with Pre => Member <= Member_Count (Shape);
   --  Return one modeled member shape.
   --  @param Shape Modeled structure shape index
   --  @param Member One-based member index
   --  @return Indexed member shape
   function Member_Shape
     (Shape : Shape_Index; Member : Positive) return Shape_Index
   with Pre => Member <= Member_Count (Shape);
   --  Return one modeled member location.
   --  @param Shape Modeled structure shape index
   --  @param Member One-based member index
   --  @return Indexed member location
   function Location
     (Shape : Shape_Index; Member : Positive) return Member_Location
   with Pre => Member <= Member_Count (Shape);
   --  Return one modeled member location name.
   --  @param Shape Modeled structure shape index
   --  @param Member One-based member index
   --  @return Location name or an empty string
   function Member_Location_Name
     (Shape : Shape_Index; Member : Positive) return String
   with Pre => Member <= Member_Count (Shape);
   --  Report whether one modeled member is required.
   --  @param Shape Modeled structure shape index
   --  @param Member One-based member index
   --  @return True when the member is required
   function Member_Required
     (Shape : Shape_Index; Member : Positive) return Boolean
   with Pre => Member <= Member_Count (Shape);
   --  Report whether one modeled member is flattened.
   --  @param Shape Modeled structure shape index
   --  @param Member One-based member index
   --  @return True when the member is flattened
   function Member_Flattened
     (Shape : Shape_Index; Member : Positive) return Boolean
   with Pre => Member <= Member_Count (Shape);
   --  Report whether one modeled member is streaming.
   --  @param Shape Modeled structure shape index
   --  @param Member One-based member index
   --  @return True when the member is streaming
   function Member_Streaming
     (Shape : Shape_Index; Member : Positive) return Boolean
   with Pre => Member <= Member_Count (Shape);
   --  Report whether one modeled member is an XML attribute.
   --  @param Shape Modeled structure shape index
   --  @param Member One-based member index
   --  @return True when the member is an XML attribute
   function Member_XML_Attribute
     (Shape : Shape_Index; Member : Positive) return Boolean
   with Pre => Member <= Member_Count (Shape);
   --  Return one modeled member XML namespace.
   --  @param Shape Modeled structure shape index
   --  @param Member One-based member index
   --  @return Namespace URI or an empty string
   function Member_XML_Namespace
     (Shape : Shape_Index; Member : Positive) return String
   with Pre => Member <= Member_Count (Shape);
   --  Return one modeled member context parameter.
   --  @param Shape Modeled structure shape index
   --  @param Member One-based member index
   --  @return Context parameter name or an empty string
   function Member_Context_Parameter
     (Shape : Shape_Index; Member : Positive) return String
   with Pre => Member <= Member_Count (Shape);

end Flyology.Object_Storage.S3.Model;
