--  Generated by tools/generate-s3-model.py; do not edit.
--  Source: pinned botocore service-2.json recorded below.
pragma Style_Checks (Off);
package Flyology.Object_Storage.S3.Model
  with SPARK_Mode => On
is

   Model_SHA256 : constant String := "429763d64912af5edae4c7a0f20a8ac3e6fecf734cde5fc465016bc8badcdef9";
   Operation_Count : constant := 116;
   Shape_Count : constant := 718;

   type Operation_Id is
     (Abort_Multipart_Upload_Operation,
      Complete_Multipart_Upload_Operation,
      Copy_Object_Operation,
      Create_Bucket_Operation,
      Create_Bucket_Metadata_Configuration_Operation,
      Create_Bucket_Metadata_Table_Configuration_Operation,
      Create_Multipart_Upload_Operation,
      Create_Session_Operation,
      Delete_Bucket_Operation,
      Delete_Bucket_Analytics_Configuration_Operation,
      Delete_Bucket_Cors_Operation,
      Delete_Bucket_Encryption_Operation,
      Delete_Bucket_Intelligent_Tiering_Configuration_Operation,
      Delete_Bucket_Inventory_Configuration_Operation,
      Delete_Bucket_Lifecycle_Operation,
      Delete_Bucket_Metadata_Configuration_Operation,
      Delete_Bucket_Metadata_Table_Configuration_Operation,
      Delete_Bucket_Metrics_Configuration_Operation,
      Delete_Bucket_Ownership_Controls_Operation,
      Delete_Bucket_Policy_Operation,
      Delete_Bucket_Replication_Operation,
      Delete_Bucket_Tagging_Operation,
      Delete_Bucket_Website_Operation,
      Delete_Object_Operation,
      Delete_Object_Annotation_Operation,
      Delete_Object_Tagging_Operation,
      Delete_Objects_Operation,
      Delete_Public_Access_Block_Operation,
      Get_Bucket_Abac_Operation,
      Get_Bucket_Accelerate_Configuration_Operation,
      Get_Bucket_Acl_Operation,
      Get_Bucket_Analytics_Configuration_Operation,
      Get_Bucket_Cors_Operation,
      Get_Bucket_Encryption_Operation,
      Get_Bucket_Intelligent_Tiering_Configuration_Operation,
      Get_Bucket_Inventory_Configuration_Operation,
      Get_Bucket_Lifecycle_Operation,
      Get_Bucket_Lifecycle_Configuration_Operation,
      Get_Bucket_Location_Operation,
      Get_Bucket_Logging_Operation,
      Get_Bucket_Metadata_Configuration_Operation,
      Get_Bucket_Metadata_Table_Configuration_Operation,
      Get_Bucket_Metrics_Configuration_Operation,
      Get_Bucket_Notification_Operation,
      Get_Bucket_Notification_Configuration_Operation,
      Get_Bucket_Ownership_Controls_Operation,
      Get_Bucket_Policy_Operation,
      Get_Bucket_Policy_Status_Operation,
      Get_Bucket_Replication_Operation,
      Get_Bucket_Request_Payment_Operation,
      Get_Bucket_Tagging_Operation,
      Get_Bucket_Versioning_Operation,
      Get_Bucket_Website_Operation,
      Get_Object_Operation,
      Get_Object_Acl_Operation,
      Get_Object_Annotation_Operation,
      Get_Object_Attributes_Operation,
      Get_Object_Legal_Hold_Operation,
      Get_Object_Lock_Configuration_Operation,
      Get_Object_Retention_Operation,
      Get_Object_Tagging_Operation,
      Get_Object_Torrent_Operation,
      Get_Public_Access_Block_Operation,
      Head_Bucket_Operation,
      Head_Object_Operation,
      List_Bucket_Analytics_Configurations_Operation,
      List_Bucket_Intelligent_Tiering_Configurations_Operation,
      List_Bucket_Inventory_Configurations_Operation,
      List_Bucket_Metrics_Configurations_Operation,
      List_Buckets_Operation,
      List_Directory_Buckets_Operation,
      List_Multipart_Uploads_Operation,
      List_Object_Annotations_Operation,
      List_Object_Versions_Operation,
      List_Objects_Operation,
      List_Objects_V2_Operation,
      List_Parts_Operation,
      Put_Bucket_Abac_Operation,
      Put_Bucket_Accelerate_Configuration_Operation,
      Put_Bucket_Acl_Operation,
      Put_Bucket_Analytics_Configuration_Operation,
      Put_Bucket_Cors_Operation,
      Put_Bucket_Encryption_Operation,
      Put_Bucket_Intelligent_Tiering_Configuration_Operation,
      Put_Bucket_Inventory_Configuration_Operation,
      Put_Bucket_Lifecycle_Operation,
      Put_Bucket_Lifecycle_Configuration_Operation,
      Put_Bucket_Logging_Operation,
      Put_Bucket_Metrics_Configuration_Operation,
      Put_Bucket_Notification_Operation,
      Put_Bucket_Notification_Configuration_Operation,
      Put_Bucket_Ownership_Controls_Operation,
      Put_Bucket_Policy_Operation,
      Put_Bucket_Replication_Operation,
      Put_Bucket_Request_Payment_Operation,
      Put_Bucket_Tagging_Operation,
      Put_Bucket_Versioning_Operation,
      Put_Bucket_Website_Operation,
      Put_Object_Operation,
      Put_Object_Acl_Operation,
      Put_Object_Annotation_Operation,
      Put_Object_Legal_Hold_Operation,
      Put_Object_Lock_Configuration_Operation,
      Put_Object_Retention_Operation,
      Put_Object_Tagging_Operation,
      Put_Public_Access_Block_Operation,
      Rename_Object_Operation,
      Restore_Object_Operation,
      Select_Object_Content_Operation,
      Update_Bucket_Metadata_Annotation_Table_Configuration_Operation,
      Update_Bucket_Metadata_Inventory_Table_Configuration_Operation,
      Update_Bucket_Metadata_Journal_Table_Configuration_Operation,
      Update_Object_Encryption_Operation,
      Upload_Part_Operation,
      Upload_Part_Copy_Operation,
      Write_Get_Object_Response_Operation);

   type HTTP_Method is
     (Delete_Method, Get_Method, Head_Method, Post_Method,
      Put_Method);

   type Shape_Kind is
     (Blob_Shape, Boolean_Shape, Integer_Shape, List_Shape,
      Long_Shape, Map_Shape, String_Shape, Structure_Shape,
      Timestamp_Shape);

   type Member_Location is
     (Body_Location, Header_Location, Headers_Location,
      Query_Location, URI_Location);

   subtype Shape_Reference is Natural range 0 .. Shape_Count;
   subtype Shape_Index is Shape_Reference range 1 .. Shape_Count;
   No_Shape : constant Shape_Reference := 0;

   function Operation_Name (Operation : Operation_Id) return String;
   function Method (Operation : Operation_Id) return HTTP_Method;
   function Request_URI (Operation : Operation_Id) return String;
   function Response_Code (Operation : Operation_Id) return Positive;
   function Input_Shape
     (Operation : Operation_Id) return Shape_Reference;
   function Output_Shape
     (Operation : Operation_Id) return Shape_Reference;
   function Error_Count (Operation : Operation_Id) return Natural;
   function Error_Shape
     (Operation : Operation_Id; Index : Positive)
      return Shape_Reference
   with Pre => Index <= Error_Count (Operation);
   function Unsigned_Payload
     (Operation : Operation_Id) return Boolean;
   function Authentication_Type
     (Operation : Operation_Id) return String;
   function Request_Checksum_Required
     (Operation : Operation_Id) return Boolean;
   function Request_Checksum_Algorithm_Member
     (Operation : Operation_Id) return String;
   function Request_Validation_Mode_Member
     (Operation : Operation_Id) return String;
   function Response_Checksum_Algorithms
     (Operation : Operation_Id) return String;

   function Shape_Name (Shape : Shape_Index) return String;
   function Kind (Shape : Shape_Index) return Shape_Kind;
   function Location_Name (Shape : Shape_Index) return String;
   function Payload_Member (Shape : Shape_Index) return String;
   function Timestamp_Format (Shape : Shape_Index) return String;
   function Pattern (Shape : Shape_Index) return String;
   function Minimum (Shape : Shape_Index) return String;
   function Maximum (Shape : Shape_Index) return String;
   function Is_Flattened (Shape : Shape_Index) return Boolean;
   function Is_Sensitive (Shape : Shape_Index) return Boolean;
   function XML_Namespace (Shape : Shape_Index) return String;
   function List_Member_Shape
     (Shape : Shape_Index) return Shape_Reference;
   function Map_Key_Shape
     (Shape : Shape_Index) return Shape_Reference;
   function Map_Value_Shape
     (Shape : Shape_Index) return Shape_Reference;
   function Enumeration_Count (Shape : Shape_Index) return Natural;
   function Enumeration_Value
     (Shape : Shape_Index; Index : Positive) return String
   with Pre => Index <= Enumeration_Count (Shape);

   function Member_Count (Shape : Shape_Index) return Natural;
   function Member_Name
     (Shape : Shape_Index; Member : Positive) return String
   with Pre => Member <= Member_Count (Shape);
   function Member_Shape
     (Shape : Shape_Index; Member : Positive) return Shape_Index
   with Pre => Member <= Member_Count (Shape);
   function Location
     (Shape : Shape_Index; Member : Positive) return Member_Location
   with Pre => Member <= Member_Count (Shape);
   function Member_Location_Name
     (Shape : Shape_Index; Member : Positive) return String
   with Pre => Member <= Member_Count (Shape);
   function Member_Required
     (Shape : Shape_Index; Member : Positive) return Boolean
   with Pre => Member <= Member_Count (Shape);
   function Member_Flattened
     (Shape : Shape_Index; Member : Positive) return Boolean
   with Pre => Member <= Member_Count (Shape);
   function Member_Streaming
     (Shape : Shape_Index; Member : Positive) return Boolean
   with Pre => Member <= Member_Count (Shape);
   function Member_XML_Attribute
     (Shape : Shape_Index; Member : Positive) return Boolean
   with Pre => Member <= Member_Count (Shape);
   function Member_XML_Namespace
     (Shape : Shape_Index; Member : Positive) return String
   with Pre => Member <= Member_Count (Shape);
   function Member_Context_Parameter
     (Shape : Shape_Index; Member : Positive) return String
   with Pre => Member <= Member_Count (Shape);

end Flyology.Object_Storage.S3.Model;
