with Flyology.Object_Storage.S3.ACL;
with Flyology.Object_Storage.S3.XML;

--  Generated by tools/s3-operation.py; do not edit.
--  Exact bounded request serializer for PutBucketAcl.
package
  Flyology.Object_Storage.S3.Generated_Put_Bucket_ACL_XML
is

   function Serialize
     (Value  : Flyology.Object_Storage.S3.ACL.Access_Control_Policy;
      Limits : Flyology.Object_Storage.S3.XML.Parse_Limits) return String;

end
  Flyology.Object_Storage.S3.Generated_Put_Bucket_ACL_XML;
