with Flyology.Object_Storage.S3.Website;
with Flyology.Object_Storage.S3.XML;

--  Generated by tools/s3-operation.py; do not edit.
--  Exact bounded request serializer for PutBucketWebsite.
package
  Flyology.Object_Storage.S3.Generated_Put_Bucket_Website_XML
is

   function Serialize
     (Value  : Flyology.Object_Storage.S3.Website.Website_Configuration;
      Limits : Flyology.Object_Storage.S3.XML.Parse_Limits) return String;

end
  Flyology.Object_Storage.S3.Generated_Put_Bucket_Website_XML;
