with Flyology.Object_Storage.S3.Inventory;
with Flyology.Object_Storage.S3.XML;

--  Generated by tools/s3-operation.py; do not edit.
--  Exact bounded request serializer for PutBucketInventoryConfiguration.
package
  Flyology.Object_Storage.S3.Generated_Put_Bucket_Inventory_Configuration_XML
is

   function Serialize
     (Value  : Flyology.Object_Storage.S3.Inventory.Inventory_Configuration;
      Limits : Flyology.Object_Storage.S3.XML.Parse_Limits) return String;

end
  Flyology.Object_Storage.S3.Generated_Put_Bucket_Inventory_Configuration_XML;
