with Flyology.Object_Storage.S3.Logging;
with Flyology.Object_Storage.S3.XML;

--  Generated by tools/s3-operation.py; do not edit.
--  Exact bounded request serializer for PutBucketLogging.
package
  Flyology.Object_Storage.S3.Generated_Put_Bucket_Logging_XML
is

   function Serialize
     (Value  : Flyology.Object_Storage.S3.Logging.Logging_Status;
      Limits : Flyology.Object_Storage.S3.XML.Parse_Limits) return String;

end
  Flyology.Object_Storage.S3.Generated_Put_Bucket_Logging_XML;
